Repository facebook/react, pull requests merged in 2018-08, with the labels that each got.

#13261 Fix a crash when using dynamic children in <option> tag
  fixtures/dom/src/components/fixtures/selects/index.js
  packages/react-dom/src/__tests__/ReactDOMOption-test.js
  packages/react-dom/src/__tests__/ReactDOMSelect-test.js
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationForms-test.js
  packages/react-dom/src/__tests__/utils/ReactDOMServerIntegrationTestUtils.js
  packages/react-dom/src/client/ReactDOMFiberOption.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
Labels: CLA Signed

#13300 Refactor validateDOMNesting a bit
  packages/react-dom/src/client/ReactDOMFiberOption.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/client/validateDOMNesting.js
Labels: CLA Signed

#13131 More helpful message when passing an element to createElement()
  packages/react/src/ReactElementValidator.js
  packages/react/src/__tests__/ReactElementValidator-test.internal.js
Labels: CLA Signed

#13295 [WIP] Add suspense fixtures for IO and CPU demo
  fixtures/suspense/cpu/.gitignore
  fixtures/suspense/cpu/README.md
  fixtures/suspense/cpu/package.json
  fixtures/suspense/cpu/public/favicon.ico
  fixtures/suspense/cpu/public/index.html
  fixtures/suspense/cpu/public/manifest.json
  fixtures/suspense/cpu/src/Charts.js
  fixtures/suspense/cpu/src/Clock.js
  fixtures/suspense/cpu/src/index.css
  fixtures/suspense/cpu/src/index.js
  fixtures/suspense/cpu/yarn.lock
  fixtures/suspense/io/.gitignore
  fixtures/suspense/io/README.md
  fixtures/suspense/io/package.json
  fixtures/suspense/io/public/favicon.ico
  fixtures/suspense/io/public/img/acdlite.jpeg
  fixtures/suspense/io/public/img/bvaughn.jpeg
  fixtures/suspense/io/public/img/flarnie.jpeg
  fixtures/suspense/io/public/img/gaearon.jpeg
  fixtures/suspense/io/public/img/sebmarkbage.jpeg
  fixtures/suspense/io/public/img/sophiebits.jpeg
  fixtures/suspense/io/public/img/trueadm.jpeg
  fixtures/suspense/io/public/index.html
  fixtures/suspense/io/public/manifest.json
  fixtures/suspense/io/src/api/data.js
  fixtures/suspense/io/src/api/index.js
  fixtures/suspense/io/src/cache.js
  fixtures/suspense/io/src/components/App.js
  fixtures/suspense/io/src/components/ContributorListPage.js
  fixtures/suspense/io/src/components/Spinner.css
  fixtures/suspense/io/src/components/Spinner.js
  fixtures/suspense/io/src/components/UserPage.js
  fixtures/suspense/io/src/index.css
  fixtures/suspense/io/src/index.js
  fixtures/suspense/io/yarn.lock
Labels: CLA Signed

#13305 Fix time slicing fixture
  fixtures/unstable-async/time-slicing/src/index.js
Labels: CLA Signed

#13241 add nodejs 10 to windows test
  appveyor.yml
Labels: CLA Signed

#13169 Remove irrelevant suggestion of a legacy method from a warning
  packages/react-dom/src/__tests__/ReactCompositeComponent-test.js
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#13173 Inject react-art renderer into react-devtools
  packages/react-art/src/ReactART.js
Labels: CLA Signed

#13310 Replace console.error() with a throw in setTimeout() as last resort exception logging
  packages/react-dom/src/__tests__/ReactErrorLoggingRecovery-test.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorLogging-test.internal.js
  scripts/jest/config.build.js
Labels: CLA Signed

#13312 Warn about rendering Generators
  packages/react-dom/src/__tests__/ReactMultiChild-test.js
  packages/react-dom/src/__tests__/ReactMultiChildReconcile-test.js
  packages/react-reconciler/src/ReactChildFiber.js
Labels: CLA Signed

#12826 Fix ambiguity in doc comment for isValidElement
  packages/react/src/ReactElement.js
Labels: CLA Signed

#13314 Suspense fixture large placeholder styling improvement
  fixtures/unstable-async/suspense/src/components/Spinner.css
  fixtures/unstable-async/suspense/src/components/Spinner.js
Labels: CLA Signed

#13317 Enhance get derived state from props state warning - #12670
  packages/react-dom/src/__tests__/ReactComponentLifeCycle-test.js
  packages/react-dom/src/__tests__/ReactDOMServerLifecycles-test.js
  packages/react-dom/src/server/ReactPartialRenderer.js
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react/src/__tests__/ReactCoffeeScriptClass-test.coffee
  packages/react/src/__tests__/ReactES6Class-test.js
  packages/react/src/__tests__/ReactTypeScriptClass-test.ts
  packages/react/src/__tests__/createReactClassIntegration-test.js
Labels: CLA Signed

#13270 Make sure that `select` has `multiple` attribute set to appropriate state before appending options
  fixtures/dom/src/components/fixtures/selects/index.js
  packages/react-dom/src/client/ReactDOMFiberComponent.js
Labels: CLA Signed

#12242 Add a regression test for #12200
  packages/react-dom/src/__tests__/ReactDOMSelect-test.js
Labels: CLA Signed

#11571 Add support for auxclick event
  packages/react-dom/src/__tests__/__snapshots__/ReactTestUtils-test.js.snap
  packages/react-dom/src/events/DOMTopLevelEventTypes.js
  packages/react-dom/src/events/SimpleEventPlugin.js
Labels: CLA Signed

#13318 refactor: remove promise on checkModule
  scripts/release/build-commands/check-package-dependencies.js
Labels: CLA Signed

#13323 Fix Prettier "No parser" warning while building
  scripts/rollup/build.js
Labels: CLA Signed

#13325 Detail: fix undefined variable on suspense fixture
  fixtures/unstable-async/suspense/src/components/UserPage.js
Labels: CLA Signed

#13335 Don't search beyond Sync roots for highest priority work
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#13340 Remove unused dependencies from workspace root.
  package.json
  yarn.lock
Labels: CLA Signed

#13343 Update attribute table
  fixtures/attribute-behavior/AttributeTableSnapshot.md
Labels: CLA Signed

#13339 Treat focusable as enumerated boolean SVG attribute
  fixtures/attribute-behavior/AttributeTableSnapshot.md
  packages/react-dom/src/shared/DOMProperty.js
Labels: CLA Signed

#13344 Bump "fbjs-scripts" to remove Babel 5 from dependencies
  package.json
  yarn.lock
Labels: CLA Signed

#13313 Profiler actualDuration bugfix
  packages/react-reconciler/src/ReactFiber.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/ReactProfilerTimer.js
  packages/react/src/__tests__/ReactProfiler-test.internal.js
Labels: CLA Signed

#12059 Improve display of filenames in component stack
  packages/shared/__tests__/describeComponentFrame-test.js
  packages/shared/describeComponentFrame.js
Labels: CLA Signed

#13351 Improve TestUtils error messages for bad first argument
  packages/react-dom/src/__tests__/ReactTestUtils-test.js
  packages/react-dom/src/test-utils/ReactTestUtils.js
Labels: CLA Signed

#13353 Fix hydration of non-string dangerousSetInnerHTML.__html
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationElements-test.js
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationReconnecting-test.js
  packages/react-dom/src/client/ReactDOMFiberComponent.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
Labels: CLA Signed

#13349 Fix typos detected by github.com/client9/misspell
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorReplay-test.internal.js
Labels: CLA Signed

#13364 Fix typo on inline comment
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#13358 Rely on bubbling for submit and reset events
  fixtures/dom/yarn.lock
  packages/react-dom/src/__tests__/ReactDOM-test.js
  packages/react-dom/src/__tests__/ReactDOMEventListener-test.js
  packages/react-dom/src/client/ReactDOMFiberComponent.js
  packages/react-dom/src/events/ReactBrowserEventEmitter.js
Labels: CLA Signed

#13374 Support tangentialPressure and twist fields of pointer events
  packages/react-dom/src/events/SyntheticPointerEvent.js
Labels: CLA Signed

#13367 Improve soundness of ReactDOMFiberInput typings
  packages/react-dom/src/client/ReactDOMFiberInput.js
  packages/react-dom/src/client/SafeValue.js
Labels: CLA Signed

#13377 Fix fixture title
  fixtures/unstable-async/suspense/public/index.html
Labels: CLA Signed

#13376 Rename SafeValue to ToStringValue
  packages/react-dom/src/client/ReactDOMFiberInput.js
  packages/react-dom/src/client/ToStringValue.js
Labels: CLA Signed

#13375 Fixtures nits
  fixtures/dom/src/components/FixtureSet.js
  fixtures/dom/src/components/Iframe.js
  fixtures/dom/src/components/fixtures/buttons/index.js
  fixtures/dom/src/components/fixtures/date-inputs/index.js
  fixtures/dom/src/components/fixtures/error-handling/index.js
  fixtures/dom/src/components/fixtures/event-pooling/index.js
  fixtures/dom/src/components/fixtures/media-events/index.js
  fixtures/dom/src/components/fixtures/mouse-events/index.js
  fixtures/dom/src/components/fixtures/password-inputs/index.js
  fixtures/dom/src/components/fixtures/selects/index.js
Labels: CLA Signed

#13361 Provide component reference in ReactDOMFiberTextarea warnings
  packages/react-dom/src/__tests__/ReactDOMTextarea-test.js
  packages/react-dom/src/client/ReactDOMFiberTextarea.js
Labels: CLA Signed

#13384 Allow the user to opt out of seeing "The above error..." addendum
  fixtures/dom/src/components/fixtures/error-handling/index.js
  fixtures/dom/src/style.css
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberErrorLogger.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/shared/invokeGuardedCallback.js
Labels: CLA Signed

#13385 Ensure arguments are coerced to strings in warnings
  packages/shared/warningWithoutStack.js
Labels: CLA Signed

#13362 Fix passing symbols and functions to textarea
  packages/react-dom/src/__tests__/ReactDOMTextarea-test.js
  packages/react-dom/src/client/ReactDOMFiberTextarea.js
Labels: CLA Signed

#13368 DOM fixture updates
  fixtures/dom/src/components/Header.js
  fixtures/dom/src/components/fixtures/home.js
  fixtures/dom/src/components/fixtures/index.js
  fixtures/dom/src/style.css
Labels: CLA Signed

#13389 Ignore symbols and functions in select tag
  packages/react-dom/src/__tests__/ReactDOMSelect-test.js
  packages/react-dom/src/client/ReactDOMFiberOption.js
  packages/react-dom/src/client/ReactDOMFiberSelect.js
Labels: CLA Signed

#13372 Warn when "false" or "true" is the value of a boolean DOM prop
  packages/react-dom/src/__tests__/ReactDOMComponent-test.js
  packages/react-dom/src/__tests__/ReactDOMInput-test.js
  packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js
Labels: CLA Signed

#13373 Fix typo in a comment
  packages/shared/reactProdInvariant.js
Labels: CLA Signed

#11696 Fix window.event in development (#11687)
  fixtures/dom/src/components/fixtures/error-handling/index.js
  packages/shared/invokeGuardedCallback.js
Labels: CLA Signed

#13401 Don't suppress jsdom error reporting in our tests
  packages/react-dom/src/__tests__/ReactErrorLoggingRecovery-test.js
  packages/react-reconciler/src/ReactFiberErrorLogger.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorLogging-test.internal.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorLogging-test.js
  scripts/jest/matchers/toWarnDev.js
  scripts/jest/setupEnvironment.js
  scripts/jest/setupTests.js
  scripts/jest/shouldIgnoreConsoleError.js
Labels: CLA Signed

#13408 Improve bad ref invariant
  packages/react-dom/src/__tests__/refs-test.js
  packages/react-reconciler/src/ReactChildFiber.js
Labels: CLA Signed

#13406 Refactor ReactErrorUtils
  packages/events/EventPluginHub.js
  packages/events/EventPluginUtils.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/shared/ReactErrorUtils.js
  packages/shared/__tests__/ReactErrorUtils-test.internal.js
  packages/shared/forks/invokeGuardedCallback.www.js
  packages/shared/forks/invokeGuardedCallbackImpl.www.js
  packages/shared/invokeGuardedCallbackImpl.js
  scripts/rollup/forks.js
Labels: CLA Signed

#12421 Improve cryptic error message when creating a component starting with a lowercase letter
  packages/react-native-renderer/src/__mocks__/ReactNativeViewConfigRegistry.js
  scripts/rollup/shims/react-native/ReactNativeViewConfigRegistry.js
Labels: CLA Signed

#12780 Avoid setting empty value on reset & submit inputs
  packages/react-dom/src/__tests__/ReactDOMInput-test.js
  packages/react-dom/src/client/ReactDOMFiberInput.js
Labels: CLA Signed

#13412 Remove unused state initialValue from ReactDOMFiberSelect
  packages/react-dom/src/client/ReactDOMFiberSelect.js
Labels: CLA Signed

#13416 fix: do not reconcile children that are iterable functions
  packages/react-dom/src/__tests__/ReactChildReconciler-test.js
  packages/shared/ReactSymbols.js
Labels: CLA Signed

#13398 React.lazy
  packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js
  packages/react/src/React.js
  packages/react/src/ReactLazy.js
Labels: CLA Signed

#13125 [Fabric] Don't pass instanceHandle to clones
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/__mocks__/FabricUIManager.js
  scripts/flow/react-native-host-hooks.js
Labels: CLA Signed

#13419 Remove unused ReactCall & ReactReturn types
  packages/shared/ReactTypes.js
Labels: CLA Signed

#13421 Update attribute table for master
  fixtures/attribute-behavior/AttributeTableSnapshot.md
Labels: CLA Signed

#13234 interaction-tracking package
  packages/interaction-tracking/README.md
  packages/interaction-tracking/index.js
  packages/interaction-tracking/npm/index.js
  packages/interaction-tracking/package.json
  packages/interaction-tracking/src/InteractionTracking.js
  packages/interaction-tracking/src/__tests__/InteractionTracking-test.internal.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fabric-fb.js
  packages/shared/forks/ReactFeatureFlags.native-fabric-oss.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  scripts/jest/matchers/interactionTracking.js
  scripts/jest/setupTests.js
  scripts/jest/spec-equivalence-reporter/setupTests.js
  scripts/rollup/bundles.js
  scripts/rollup/modules.js
Labels: CLA Signed, Type: Discussion

#13423 Don't diff memoized host components in completion phase
  packages/react-dom/src/__tests__/ReactDOMFiber-test.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/__tests__/ReactIncrementalUpdatesMinimalism-test.js
  packages/react-reconciler/src/__tests__/__snapshots__/ReactIncrementalPerf-test.internal.js.snap
Labels: CLA Signed

#13427 Refactor away some namespace imports
  packages/events/EventPluginUtils.js
  packages/events/ReactControlledComponent.js
  packages/events/ReactGenericBatching.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMClientInjection.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/unstable-native-dependencies/ReactDOMUnstableNativeDependencies.js
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactFabricInjection.js
  packages/react-native-renderer/src/ReactNativeInjection.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
Labels: CLA Signed

#13426 Add interaction-tracking/subscriptions
  packages/interaction-tracking/package.json
  packages/interaction-tracking/src/InteractionTracking.js
  packages/interaction-tracking/src/InteractionTrackingSubscriptions.js
  packages/interaction-tracking/src/__tests__/InteractionTracking-test.internal.js
  packages/interaction-tracking/src/__tests__/InteractionTrackingSubscriptions-test.internal.js
  packages/interaction-tracking/subscriptions.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fabric-fb.js
  packages/shared/forks/ReactFeatureFlags.native-fabric-oss.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  scripts/rollup/bundles.js
  scripts/rollup/modules.js
Labels: CLA Signed

#11927 Trap click events for portal root
  packages/react-dom/src/client/ReactDOMFiberComponent.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
Labels: CLA Signed

#13428 Do not toLowerCase lists of lowercase words
  packages/react-dom/src/shared/DOMProperty.js
Labels: CLA Signed

#13430 Remove helper object from FallbackCompositionState
  packages/react-dom/src/events/FallbackCompositionState.js
Labels: CLA Signed

#13435 Remove addEventListener check in isEventSupported
  packages/react-dom/src/events/ReactBrowserEventEmitter.js
  packages/react-dom/src/events/isEventSupported.js
Labels: CLA Signed, Needs Browser Testing

#13434 Remove getTextContentAccessor
  packages/react-dom/src/client/ReactDOMSelection.js
  packages/react-dom/src/client/getTextContentAccessor.js
  packages/react-dom/src/events/FallbackCompositionState.js
Labels: CLA Signed, Needs Browser Testing

#13392 Short circuit the logic for exporting a module
  packages/react-dom/index.fb.js
  packages/react-dom/index.js
  packages/react-dom/server.browser.js
  packages/react-dom/server.node.js
  packages/react-dom/test-utils.js
  packages/react-native-renderer/fabric.js
  packages/react-native-renderer/index.js
  packages/react-noop-renderer/index.js
  packages/react-noop-renderer/persistent.js
  packages/react-reconciler/index.js
  packages/react-reconciler/persistent.js
  packages/react-test-renderer/index.js
  packages/react-test-renderer/shallow.js
  packages/react/index.js
Labels: CLA Signed

#13441 Fix incorrect legacy context for factory components
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react-reconciler/src/ReactFiberContext.js
  packages/react-reconciler/src/__tests__/ReactIncremental-test.internal.js
Labels: CLA Signed

#13443 Fix component name for React.lazy
  packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js
  packages/shared/getComponentName.js
Labels: CLA Signed

#13444 Tweak ReactTypeOfWork order
  packages/shared/ReactTypeOfWork.js
Labels: CLA Signed

#13446 Fix React.lazy(forwardRef)
  .eslintrc.js
  packages/react-reconciler/src/ReactFiberLazyComponent.js
  packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js
Labels: CLA Signed

#12895 ReactTestRenderer and ReactDOM portals
  packages/react-test-renderer/src/ReactTestHostConfig.js
  packages/react-test-renderer/src/__tests__/ReactTestRenderer-test.js
Labels: CLA Signed

#13437 Update scroll restoration logic in suspense fixture
  fixtures/unstable-async/suspense/src/components/App.js
Labels: CLA Signed

#13448 Bumped version to 16.4.3-alpha.0
  package.json
  packages/create-subscription/package.json
  packages/react-art/package.json
  packages/react-dom/package.json
  packages/react-is/package.json
  packages/react-test-renderer/package.json
  packages/react/package.json
  packages/shared/ReactVersion.js
Labels: CLA Signed

#12457 Warn about unsafe toWarnDev() nesting in tests
  .eslintrc.js
  packages/react-dom/src/__tests__/ReactCompositeComponent-test.js
  packages/react-dom/src/__tests__/ReactDOMTextarea-test.js
  packages/react-dom/src/__tests__/ReactServerRendering-test.js
  scripts/eslint-rules/__tests__/no-to-warn-dev-within-to-throw-test.internal.js
  scripts/eslint-rules/index.js
  scripts/eslint-rules/no-to-warn-dev-within-to-throw.js
  scripts/jest/matchers/__tests__/toWarnDev-test.js
Labels: CLA Signed

#13454 Change www error shim API
  packages/shared/forks/invokeGuardedCallbackImpl.www.js
Labels: CLA Signed

#13462 Revert "Rely on bubbling for submit and reset events (#13358)"
  fixtures/dom/yarn.lock
  packages/react-dom/src/__tests__/ReactDOM-test.js
  packages/react-dom/src/__tests__/ReactDOMEventListener-test.js
  packages/react-dom/src/client/ReactDOMFiberComponent.js
  packages/react-dom/src/events/ReactBrowserEventEmitter.js
Labels: CLA Signed

#13463 Improve test harness of submit events
  fixtures/dom/yarn.lock
  packages/react-dom/src/__tests__/ReactDOM-test.js
  packages/react-dom/src/__tests__/ReactDOMEventListener-test.js
Labels: CLA Signed

#13474 Correct syntax in CHANGELOG
  CHANGELOG.md
Labels: CLA Signed

#13476 Rename ReactTypeOfWork to ReactWorkTags, ReactTypeOfSideEffect to ReactSideEffectTags
  packages/events/__tests__/ResponderEventPlugin-test.internal.js
  packages/react-dom/src/client/ReactDOMComponentTree.js
  packages/react-dom/src/events/ReactDOMEventListener.js
  packages/react-dom/src/test-utils/ReactTestUtils.js
  packages/react-native-renderer/src/ReactNativeFiberInspector.js
  packages/react-reconciler/src/ReactChildFiber.js
  packages/react-reconciler/src/ReactCurrentFiber.js
  packages/react-reconciler/src/ReactDebugFiberPerf.js
  packages/react-reconciler/src/ReactFiber.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberContext.js
  packages/react-reconciler/src/ReactFiberHydrationContext.js
  packages/react-reconciler/src/ReactFiberNewContext.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/ReactFiberTreeReflection.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/ReactUpdateQueue.js
  packages/react-test-renderer/src/ReactTestRenderer.js
  packages/shared/ReactSideEffectTags.js
  packages/shared/ReactTreeTraversal.js
  packages/shared/ReactWorkTags.js
Labels: CLA Signed

#13479 Replace magic number 1 with ELEMENT_NODE
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/shared/HTMLNodeType.js
  packages/react-dom/src/test-utils/ReactTestUtils.js
Labels: CLA Signed

#13481 [SSR Fixture] Update yarn.lock
  fixtures/ssr/yarn.lock
Labels: CLA Signed

#13484 Rename lowestPendingInteractiveExpirationTime
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#11658 Add warning to prevent setting this.state to this.props referentially
  packages/react-dom/src/__tests__/ReactComponentLifeCycle-test.js
  packages/react-reconciler/src/ReactFiberClassComponent.js
Labels: CLA Signed

#13495 added flow types to setInnerHTML
  packages/react-dom/src/client/setInnerHTML.js
Labels: CLA Signed

#13488 Remove buggy unstable_deferredUpdates()
  fixtures/unstable-async/suspense/src/components/App.js
  fixtures/unstable-async/time-slicing/src/index.js
  packages/react-dom/src/__tests__/ReactDOMFiberAsync-test.internal.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#13253 Profiler integration with interaction-tracking package
  fixtures/unstable-async/suspense/package.json
  fixtures/unstable-async/suspense/src/components/App.js
  fixtures/unstable-async/suspense/src/index.js
  fixtures/unstable-async/suspense/yarn.lock
  packages/react-reconciler/src/ReactFiber.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberRoot.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react/src/__tests__/ReactProfiler-test.internal.js
  packages/react/src/__tests__/ReactProfilerDevToolsIntegration-test.internal.js
  packages/react/src/__tests__/__snapshots__/ReactProfiler-test.internal.js.snap
  packages/shared/ReactFeatureFlags.js
  scripts/rollup/bundles.js
  scripts/rollup/modules.js
Labels: CLA Signed, Type: Discussion

#13513 Sync React Native Flow Changes
  packages/react-native-renderer/src/NativeMethodsMixin.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeAttributePayload.js
  packages/react-native-renderer/src/ReactNativeComponent.js
  packages/react-native-renderer/src/ReactNativeFiberHostComponent.js
  packages/react-native-renderer/src/ReactNativeHostConfig.js
  packages/react-native-renderer/src/ReactNativeTypes.js
  packages/react-native-renderer/src/__mocks__/ReactNativeViewConfigRegistry.js
  packages/shared/ReactFeatureFlags.js
  scripts/rollup/shims/react-native/createReactNativeComponentClass.js
Labels: CLA Signed

#13511 [RN] Remove isMounted() false positive warning
  packages/react-native-renderer/src/NativeMethodsMixin.js
  packages/react-native-renderer/src/NativeMethodsMixinUtils.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeComponent.js
  packages/react-native-renderer/src/ReactNativeFiberHostComponent.js
Labels: CLA Signed

#13519 Fixed typos
  packages/react-dom/src/client/ReactDOM.js
  scripts/bench/build.js
Labels: CLA Signed
