Repository facebook/react, pull requests merged in 2019-05, with the labels that each got.

#15560 Event API: Support press reentry for pointer events
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed

#15562 React Events: cancel onLongPress for large enough moves
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15563 React Events: fix cancel events for Press
  packages/react-events/docs/Press.md
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15385 Ensure TouchHitTarget element is server side rendered with hit slop
  packages/react-dom/src/client/ReactDOMComponent.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/server/ReactPartialRenderer.js
  packages/react-dom/src/shared/DOMProperty.js
  packages/react-events/src/__tests__/TouchHitTarget-test.internal.js
Labels: CLA Signed, React Flare

#15567 Fix interaction tracing for batched update mounts
  package.json
  packages/react-dom/src/__tests__/ReactTestUtilsAct-test.js
  packages/react-dom/src/__tests__/ReactUpdates-test.js
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#15580 Add React.unstable_createEventComponent
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-events/README.md
  packages/react-events/package.json
  packages/react-events/src/Drag.js
  packages/react-events/src/Focus.js
  packages/react-events/src/FocusScope.js
  packages/react-events/src/Hover.js
  packages/react-events/src/Press.js
  packages/react-events/src/Swipe.js
  packages/react/src/React.js
  packages/react/src/ReactCreateEventComponent.js
  scripts/rollup/bundles.js
Labels: CLA Signed, React Flare

#15492 Warn when suspending at wrong priority
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
Labels: CLA Signed

#15578 Add Suspense Boundary Context (and unstable_avoidThisFallback)
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberSuspenseComponent.js
  packages/react-reconciler/src/ReactFiberSuspenseContext.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
Labels: CLA Signed

#15587 Ensure touch events are properly handled for pageX and pageY
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15590 Experimental Event API: reduce code size of event modules
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/src/Focus.js
  packages/react-events/src/Hover.js
  packages/react-events/src/Press.js
  packages/react-events/src/utils.js
  packages/shared/ReactTypes.js
Labels: CLA Signed

#15586 Experimental Event API: Press event properties
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15597 Event API: add more warnings for responder based events
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
Labels: CLA Signed, React Flare

#15598 Event API: normalize event timeStamp property to be in event system
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
  packages/react-events/src/Drag.js
  packages/react-events/src/Focus.js
  packages/react-events/src/Hover.js
  packages/react-events/src/Press.js
  packages/react-events/src/Swipe.js
  packages/shared/ReactTypes.js
Labels: CLA Signed, React Flare

#15599 Event API: ensure we pop context for event system fibers
  packages/react-reconciler/src/ReactFiberUnwindWork.js
Labels: CLA Signed

#15611 Event API: add key modifiers to Press events
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15612 Event API: add follow up event unwind test
  packages/react-reconciler/src/__tests__/ReactFiberEvents-test-internal.js
Labels: CLA Signed, React Flare

#15606 Don't consider "Never" expiration as part of most recent event time
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/__tests__/ReactSuspensePlaceholder-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
Labels: CLA Signed

#15633 Event API: ensure preventDefault works for nested targets
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
  packages/shared/ReactTypes.js
Labels: CLA Signed

#15502 Add Batched Mode
  packages/react-art/src/ReactART.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/fire/ReactFire.js
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiber.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberExpirationTime.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberRoot.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/ReactTypeOfMode.js
  packages/react-reconciler/src/SchedulerWithReactIntegration.js
  packages/react-reconciler/src/__tests__/ReactBatchedMode-test.internal.js
  packages/react-reconciler/src/__tests__/ReactFiberHostContext-test.internal.js
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseFuzz-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspensePlaceholder-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
  packages/react-test-renderer/src/ReactTestRenderer.js
  packages/shared/ReactRootTags.js
Labels: CLA Signed

#15504 Add ReactDOM.unstable_createSyncRoot
  packages/react-dom/src/__tests__/ReactDOMFiberAsync-test.internal.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/fire/ReactFire.js
Labels: CLA Signed

#15532 Remove <React.unstable_ConcurrentMode /> element type
  fixtures/unstable-async/time-slicing/src/index.js
  packages/react-dom/src/__tests__/ReactDOMFiberAsync-test.internal.js
  packages/react-dom/src/__tests__/ReactDOMHooks-test.js
  packages/react-dom/src/__tests__/ReactDOMRoot-test.js
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationModes-test.js
  packages/react-dom/src/events/__tests__/SimpleEventPlugin-test.internal.js
  packages/react-is/README.md
  packages/react-is/src/__tests__/ReactIs-test.js
  packages/react-reconciler/src/__tests__/ReactIncrementalPerf-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
  packages/react-reconciler/src/__tests__/__snapshots__/ReactIncrementalPerf-test.internal.js.snap
  packages/react/src/React.js
  packages/react/src/__tests__/ReactStrictMode-test.internal.js
  packages/shared/ReactSymbols.js
  packages/shared/getComponentName.js
Labels: CLA Signed

#15517 Invariant that throws when committing wrong tree
  packages/react-reconciler/src/ReactFiberRoot.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#15645 Event API: adds pointerType to Focus events
  packages/react-events/src/Focus.js
  packages/react-events/src/__tests__/Focus-test.internal.js
Labels: CLA Signed, React Flare

#15636 Add test for nested avoided boundaries
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
Labels: CLA Signed

#15651 Event API: ensure getFocusableElementsInScope handles suspended trees
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/shared/assertValidProps.js
  packages/react-events/src/__tests__/FocusScope-test.internal.js
Labels: CLA Signed, React Flare

#15650 Fix serial passive effects
  packages/react-dom/src/__tests__/ReactDOMHooks-test.js
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/__tests__/ReactHooks-test.internal.js
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.internal.js
Labels: CLA Signed

#15659 Feature flag to revert #15650
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.internal.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed

#15662 Use dynamic flag in test renderer in www
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
Labels: CLA Signed

#15614 Fix <embed> not triggering onLoad
  packages/react-dom/src/__tests__/ReactDOMEventListener-test.js
  packages/react-dom/src/client/ReactDOMComponent.js
Labels: CLA Signed

#15666 Bail out of updates in offscreen trees
  packages/react-dom/src/__tests__/ReactUpdates-test.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/__tests__/ReactIncrementalSideEffects-test.internal.js
Labels: CLA Signed

#15671 Event API: ensure calculateResponderRegion accounts for page offset
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed

#15591 `act()` - s / flushPassiveEffects / Scheduler.unstable_flushWithoutYielding
  fixtures/dom/.gitignore
  fixtures/dom/package.json
  fixtures/dom/public/act-dom.html
  packages/react-dom/src/__tests__/ReactTestUtilsAct-test.internal.js
  packages/react-dom/src/__tests__/ReactTestUtilsAct-test.js
  packages/react-dom/src/test-utils/ReactTestUtilsAct.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/__tests__/ReactBatchedMode-test.internal.js
  packages/react-reconciler/src/__tests__/ReactHooks-test.internal.js
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.internal.js
  packages/react-reconciler/src/__tests__/ReactIncrementalScheduling-test.internal.js
  packages/react-reconciler/src/__tests__/ReactNoopRendererAct-test.js
  packages/react-test-renderer/src/ReactTestRendererAct.js
  packages/scheduler/src/forks/SchedulerHostConfig.mock.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  packages/shared/forks/Scheduler.umd.js
  scripts/rollup/bundles.js
Labels: CLA Signed, Component: Test Utils

#15672 Event API: isTargetWithinEventResponderScope on unmounted event components
  packages/react-dom/src/events/DOMEventResponderSystem.js
Labels: CLA Signed, React Flare

#15646 Event API: Add responder allowMultipleHostChildren flag
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
  packages/react-events/src/Drag.js
  packages/react-events/src/Focus.js
  packages/react-events/src/FocusScope.js
  packages/react-events/src/Hover.js
  packages/react-events/src/Press.js
  packages/react-events/src/Swipe.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberEvents.js
  packages/shared/ReactTypes.js
Labels: CLA Signed, React Flare

#15593 Add withSuspenseConfig API
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/fire/ReactFire.js
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberExpirationTime.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberNewContext.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/ReactFiberSuspenseConfig.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/ReactUpdateQueue.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
  packages/react/src/React.js
  packages/react/src/ReactBatchConfig.js
  packages/react/src/ReactCurrentBatchConfig.js
  packages/react/src/ReactSharedInternals.js
  packages/shared/ReactSharedInternals.js
Labels: CLA Signed

#15619 [Fresh] Set up initial scaffolding
  packages/react-dom/src/__tests__/ReactFresh-test.internal.js
  packages/react-reconciler/src/ReactChildFiber.js
  packages/react-reconciler/src/ReactFiber.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberHotReloading.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorReplay-test.internal.js
Labels: CLA Signed

#15681 [Fresh] Support lazy() and add Suspense tests
  packages/react-dom/src/__tests__/ReactFresh-test.internal.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
Labels: CLA Signed

#15685 [Fresh] Don't traverse remounted trees
  packages/react-dom/src/__tests__/ReactFresh-test.internal.js
  packages/react-reconciler/src/ReactFiberHotReloading.js
Labels: CLA Signed

#15686 [Fresh] Support re-rendering lazy() without losing state
  packages/react-dom/src/__tests__/ReactFresh-test.internal.js
  packages/react-reconciler/src/ReactFiberHotReloading.js
Labels: CLA Signed

#15664 Inform DevTools of commit priority level
  packages/react-reconciler/src/ReactFiberDevToolsHook.js
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#15682 flush only on exiting outermost act()
  packages/react-dom/src/__tests__/ReactTestUtilsAct-test.js
  packages/react-dom/src/test-utils/ReactTestUtilsAct.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-test-renderer/src/ReactTestRendererAct.js
Labels: CLA Signed

#15693 Flare: update invalid accessor warnings + add no-ops
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
Labels: CLA Signed, React Flare

#15694 Flare: simplify dispatchEvent discrete argument
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
  packages/react-events/src/Drag.js
  packages/react-events/src/Focus.js
  packages/react-events/src/Hover.js
  packages/react-events/src/Press.js
  packages/react-events/src/Swipe.js
  packages/shared/ReactTypes.js
Labels: CLA Signed, React Flare

#15698 [Fresh] Set up infra for runtime and Babel plugin
  packages/react-fresh/README.md
  packages/react-fresh/babel.js
  packages/react-fresh/npm/babel.js
  packages/react-fresh/npm/runtime.js
  packages/react-fresh/package.json
  packages/react-fresh/runtime.js
  packages/react-fresh/src/ReactFreshBabelPlugin.js
  packages/react-fresh/src/ReactFreshRuntime.js
  packages/react-fresh/src/__tests__/ReactFresh-test.js
  packages/react-fresh/src/__tests__/ReactFreshBabelPlugin-test.js
  packages/react-fresh/src/__tests__/__snapshots__/ReactFreshBabelPlugin-test.js.snap
  packages/react-reconciler/src/ReactFiberHotReloading.js
  scripts/rollup/bundles.js
Labels: CLA Signed

#15687 [Flare] Update interactiveUpdates flushing heuristics
  packages/events/ReactGenericBatching.js
  packages/react-dom/src/__tests__/ReactDOMFiber-test.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/ReactDOMEventListener.js
  packages/react-dom/src/fire/ReactFire.js
  packages/react-events/src/__tests__/Press-test.internal.js
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
Labels: CLA Signed, React Flare

#15699 Rename "loading" to "busy" in SuspenseConfig API
  packages/react-reconciler/src/ReactFiberScheduler.js
  packages/react-reconciler/src/ReactFiberSuspenseConfig.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
Labels: CLA Signed

#15700 Fix missing return pointer assignment
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/__tests__/ReactSuspenseFuzz-test.internal.js
Labels: CLA Signed

#15702 Flare: change flushDiscreteUpdates invariant to warning
  packages/react-dom/src/__tests__/ReactDOMFiber-test.js
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: React Flare

#15692 Fix ReactFiberNewContext spelling
  packages/react-reconciler/src/ReactFiberNewContext.js
  packages/react-reconciler/src/ReactFiberScheduler.js
Labels: CLA Signed

#15704 Parallelize CircleCI jobs using workflows
  .circleci/config.yml
  scripts/circleci/test_entry_point.sh
Labels: CLA Signed

#15707 [Flare] Account for fixed elements in getAbsoluteBoundingClientRect
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15708 [Flare] update getEventCurrentTarget to use fiber tree
  packages/react-dom/src/events/DOMEventResponderSystem.js
Labels: CLA Signed, React Flare

#15710 Fix Flow
  packages/react-events/src/Press.js
Labels: CLA Signed

#15712 Always run yarn after restoring modules cache
  .circleci/config.yml
Labels: CLA Signed

#15713 Remove redundant test run
  .circleci/config.yml
Labels: CLA Signed

#15711 [Fresh] Initial Babel plugin implementation
  packages/react-fresh/src/ReactFreshBabelPlugin.js
  packages/react-fresh/src/__tests__/ReactFreshBabelPlugin-test.js
  packages/react-fresh/src/__tests__/__snapshots__/ReactFreshBabelPlugin-test.js.snap
Labels: CLA Signed

#15714 Update sizebot to match name of CircleCI build job
  .circleci/config.yml
  dangerfile.js
Labels: CLA Signed

#15717 [Flare] event component displayName is now mandatory
  packages/shared/ReactTypes.js
  packages/shared/getComponentName.js
Labels: CLA Signed, React Flare

#15604 [react-native] Use path-based imports instead of Haste for the RN renderer
  packages/react-native-renderer/src/NativeMethodsMixin.js
  packages/react-native-renderer/src/ReactFabricGlobalResponderHandler.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeAttributePayload.js
  packages/react-native-renderer/src/ReactNativeBridgeEventPlugin.js
  packages/react-native-renderer/src/ReactNativeComponent.js
  packages/react-native-renderer/src/ReactNativeFiberHostComponent.js
  packages/react-native-renderer/src/ReactNativeFiberInspector.js
  packages/react-native-renderer/src/ReactNativeGlobalResponderHandler.js
  packages/react-native-renderer/src/ReactNativeHostConfig.js
  packages/react-native-renderer/src/ReactNativeInjection.js
  packages/react-native-renderer/src/ReactNativeInjectionShared.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-native-renderer/src/ReactNativeRendererSharedExports.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/BatchedBridge.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ExceptionsManager.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/InitializeNativeFabricUIManager.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/Platform.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/RCTEventEmitter.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativeViewConfigRegistry.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/TextInputState.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/UIManager.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/deepDiffer.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/deepFreezeAndThrowOnMutationInDev.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/flattenStyle.js
  packages/react-native-renderer/src/__tests__/ReactFabric-test.internal.js
  packages/react-native-renderer/src/__tests__/ReactFabricAndNative-test.internal.js
  packages/react-native-renderer/src/__tests__/ReactNativeError-test.internal.js
  packages/react-native-renderer/src/__tests__/ReactNativeEvents-test.internal.js
  packages/react-native-renderer/src/__tests__/ReactNativeMount-test.internal.js
  packages/react-native-renderer/src/__tests__/createReactNativeComponentClass-test.internal.js
  packages/react-reconciler/src/forks/ReactFiberErrorDialog.native.js
  scripts/flow/react-native-host-hooks.js
  scripts/rollup/bundles.js
  scripts/rollup/modules.js
Labels: CLA Signed

#15720 [Flare] Ensure getAbsoluteBoundingClientRect aligns with offsetParent
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed

#15718 Set up cron job to run fuzz tester
  .circleci/config.yml
  packages/react-reconciler/src/__tests__/ReactSuspenseFuzz-test.internal.js
Labels: CLA Signed

#15725 Rename ReactFiberScheduler -> ReactFiberWorkLoop and extract throwException from Unwind
  packages/react-dom/src/test-utils/ReactTestUtils.js
  packages/react-dom/src/test-utils/ReactTestUtilsAct.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberDevToolsHook.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberHotReloading.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberRoot.js
  packages/react-reconciler/src/ReactFiberThrow.js
  packages/react-reconciler/src/ReactFiberUnwindWork.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/ReactUpdateQueue.js
  packages/react-test-renderer/src/ReactTestRendererAct.js
Labels: CLA Signed

#15724 [Fresh] Babel plugin now handles HOCs + add integration tests
  packages/react-fresh/src/ReactFreshBabelPlugin.js
  packages/react-fresh/src/__tests__/ReactFresh-test.js
  packages/react-fresh/src/__tests__/ReactFreshBabelPlugin-test.js
  packages/react-fresh/src/__tests__/ReactFreshIntegration-test.js
  packages/react-fresh/src/__tests__/__snapshots__/ReactFreshBabelPlugin-test.js.snap
Labels: CLA Signed

#15735 [sizebot] Remove sizebot race condition
  dangerfile.js
Labels: CLA Signed

#15746 [Flare] More fixes for getAbsoluteBoundingClientRect
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15750 [Flare] Deeply prevent default on anchor elements
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
  packages/shared/ReactTypes.js
Labels: CLA Signed, React Flare

#15747 Adds test for #15732.
  packages/react-reconciler/src/__tests__/ReactHooks-test.internal.js
Labels: CLA Signed

#15641 Fix double spaces in error-codes/codes.json
  scripts/error-codes/codes.json
Labels: CLA Signed

#15734 [Suspense] Add Batched Mode variant to fuzz tester
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/__tests__/ReactSuspenseFuzz-test.internal.js
Labels: CLA Signed

#15755 Remove 5 second safety limit
  packages/react-reconciler/src/ReactFiberWorkLoop.js
Labels: CLA Signed

#15733 [Fresh] Generate signatures for Hooks
  packages/react-fresh/src/ReactFreshBabelPlugin.js
  packages/react-fresh/src/ReactFreshRuntime.js
  packages/react-fresh/src/__tests__/ReactFresh-test.js
  packages/react-fresh/src/__tests__/ReactFreshBabelPlugin-test.js
  packages/react-fresh/src/__tests__/ReactFreshIntegration-test.js
  packages/react-fresh/src/__tests__/__snapshots__/ReactFreshBabelPlugin-test.js.snap
Labels: CLA Signed

#15761 [Flare] Adds onContextMenu and fixes some contextmenu related issues
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#15757 Lint rule for unminified errors
  package.json
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/InitializeNativeFabricUIManager.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativeViewConfigRegistry.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/UIManager.js
  packages/react-reconciler/src/ReactFiberHostConfig.js
  packages/react-stream/src/ReactFizzFormatConfig.js
  packages/react-stream/src/ReactFizzHostConfig.js
  scripts/error-codes/README.md
  scripts/error-codes/codes.json
  scripts/eslint-rules/__tests__/warning-and-invariant-args-test.internal.js
  scripts/eslint-rules/warning-and-invariant-args.js
  scripts/rollup/shims/react-native/ReactNativeViewConfigRegistry.js
Labels: CLA Signed

#15758 Don't extract errors in CI
  .circleci/config.yml
  scripts/circleci/build.sh
  scripts/circleci/check_minified_errors.sh
  scripts/error-codes/__tests__/__snapshots__/transform-error-messages.js.snap
  scripts/error-codes/transform-error-messages.js
Labels: CLA Signed

#15716 Parallelizes the build script across multiple processes
  .circleci/config.yml
  .gitignore
  scripts/circleci/upload_build.sh
  scripts/rollup/build.js
  scripts/rollup/consolidateBundleSizes.js
  scripts/rollup/stats.js
Labels: CLA Signed

#15767 Update name of CI job in sizebot
  .circleci/config.yml
  dangerfile.js
Labels: CLA Signed

#15756 using the wrong renderer's act() should warn
  .circleci/config.yml
  fixtures/dom/package.json
  fixtures/dom/public/act-dom.html
  fixtures/dom/src/index.test.js
  package.json
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/fire/ReactFire.js
  packages/react-dom/src/test-utils/ReactTestUtils.js
  packages/react-dom/src/test-utils/ReactTestUtilsAct.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-test-renderer/src/ReactTestRendererAct.js
  packages/react/src/ReactCurrentActingRendererSigil.js
  packages/react/src/ReactSharedInternals.js
Labels: CLA Signed

#15766 [Flare] Support legacy browser Spacebar key value
  packages/react-events/src/Press.js
Labels: CLA Signed, React Flare

#15768 React Events: check window before using navigator
  packages/react-events/src/Press.js
Labels: CLA Signed

#15771 Fix sizebot
  scripts/rollup/build.js
  scripts/rollup/consolidateBundleSizes.js
  scripts/rollup/stats.js
Labels: CLA Signed

#15769 [Suspense] Change Suspending and Restarting Heuristics
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberExpirationTime.js
  packages/react-reconciler/src/ReactFiberSuspenseComponent.js
  packages/react-reconciler/src/ReactFiberThrow.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactIncrementalPerf-test.internal.js
  packages/react-reconciler/src/__tests__/ReactLazy-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspensePlaceholder-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
  packages/react-reconciler/src/__tests__/__snapshots__/ReactIncrementalPerf-test.internal.js.snap
  packages/react/src/__tests__/ReactProfiler-test.internal.js
Labels: CLA Signed

#15679 Fix issue with Tab+alt not being considered as isGlobalFocusVisible c…
  packages/react-events/src/Focus.js
  packages/react-events/src/__tests__/Focus-test.internal.js
Labels: CLA Signed

#15795 [Flare] Remove deprecated keypress event
  packages/react-events/src/Focus.js
  packages/react-events/src/Press.js
  packages/react-events/src/__tests__/Focus-test.internal.js
Labels: CLA Signed, React Flare
