Repository facebook/react, pull requests merged in 2019-09, with the labels that each got.

#16633 fix typo
  packages/react-dom/src/__tests__/ReactDOMFiberAsync-test.internal.js
Labels: CLA Signed

#16612 [DevTools] [Profiler]: Save profile now working in Firefox
  packages/react-devtools-shared/src/devtools/views/Profiler/ProfilingImportExportButtons.js
  packages/react-devtools-shared/src/devtools/views/utils.js
Labels: CLA Signed

#16642 [react-events] Adds preventKeys support to Keyboard responder
  packages/react-events/src/dom/Keyboard.js
  packages/react-events/src/dom/__tests__/Keyboard-test.internal.js
Labels: CLA Signed, React Flare

#16654 [react-events] Various core tweaks for event responder system
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
  packages/react-events/README.md
  packages/react-events/src/dom/Focus.js
  packages/react-events/src/dom/Hover.js
  packages/react-events/src/dom/Input.js
  packages/react-events/src/dom/Keyboard.js
  packages/react-events/src/dom/Press.js
  packages/react-events/src/rn/Press.js
  packages/react-native-renderer/src/ReactFabricEventResponderSystem.js
  packages/react-native-renderer/src/ReactNativeTypes.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberEvents.js
  packages/react-reconciler/src/__tests__/ReactScope-test.internal.js
  packages/shared/ReactDOMTypes.js
  packages/shared/ReactTypes.js
Labels: CLA Signed, React Flare

#16657 [react-events] Keyboard responder propagation handling
  packages/legacy-events/ReactGenericBatching.js
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/src/dom/Keyboard.js
  packages/react-events/src/dom/__tests__/Keyboard-test.internal.js
  packages/shared/ReactDOMTypes.js
Labels: CLA Signed, React Flare

#16658 [react-events] Fix Scope listener issue
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberEvents.js
  packages/react-reconciler/src/__tests__/ReactScope-test.internal.js
Labels: CLA Signed, React Flare

#16660 [react-events] Refactor getCurrentTarget to getResponderNode
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
  packages/react-events/src/dom/Focus.js
  packages/react-events/src/dom/Hover.js
  packages/react-events/src/dom/Input.js
  packages/react-events/src/dom/Keyboard.js
  packages/react-events/src/dom/Press.js
  packages/react-events/src/rn/Press.js
  packages/react-native-renderer/src/ReactFabricEventResponderSystem.js
  packages/react-native-renderer/src/ReactNativeTypes.js
  packages/shared/ReactDOMTypes.js
Labels: CLA Signed, React Flare

#16662 [react-events] Refine executeUserEventHandler
  packages/legacy-events/ReactGenericBatching.js
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/src/dom/Keyboard.js
Labels: CLA Signed, React Flare

#16628 [react-events] Tap responder
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/npm/tap.js
  packages/react-events/package.json
  packages/react-events/src/dom/Press.js
  packages/react-events/src/dom/Tap.js
  packages/react-events/src/dom/__tests__/Tap-test.internal.js
  packages/react-events/src/dom/shared/index.js
  packages/react-events/src/dom/testing-library/domEnvironment.js
  packages/react-events/src/dom/testing-library/domEventSequences.js
  packages/react-events/src/dom/testing-library/domEvents.js
  packages/react-events/src/dom/testing-library/index.js
  packages/react-events/tap.js
  packages/shared/ReactDOMTypes.js
  scripts/rollup/bundles.js
Labels: CLA Signed, React Flare

#16591 [Partial Hydration] Don't invoke listeners on parent of dehydrated event target
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMComponentTree.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/events/EnterLeaveEventPlugin.js
  packages/react-dom/src/events/ReactDOMEventListener.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  packages/react-reconciler/src/ReactFiberHydrationContext.js
  packages/react-reconciler/src/ReactFiberTreeReflection.js
  packages/react-reconciler/src/forks/ReactFiberHostConfig.custom.js
  packages/shared/HostConfigWithNoHydration.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#16647 Use www Flag version for warnAboutStringRefs and warnAboutDefaultPropsOnFunctionComponents
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed

#16623 use-subscription tearing fix
  packages/use-subscription/src/__tests__/useSubscription-test.internal.js
  packages/use-subscription/src/useSubscription.js
Labels: CLA Signed

#16408 Enable MessageLoop implementation by default
  packages/scheduler/src/SchedulerFeatureFlags.js
  packages/scheduler/src/__tests__/SchedulerRAFOld-test.internal.js
  packages/scheduler/src/forks/SchedulerFeatureFlags.www.js
Labels: CLA Signed

#16671 [react-events] Fix isTargetWithinNode type
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/src/dom/Tap.js
  packages/shared/ReactDOMTypes.js
Labels: CLA Signed, React Flare

#16672 Remove experimental scheduler flags
  packages/scheduler/src/SchedulerFeatureFlags.js
  packages/scheduler/src/forks/SchedulerFeatureFlags.www.js
  packages/scheduler/src/forks/SchedulerHostConfig.default.js
Labels: CLA Signed

#16673 Check for Suspense boundary in a root Container
  packages/react-dom/src/client/ReactDOMComponentTree.js
Labels: CLA Signed

#16680 Fix typo: wnless -> unless
  packages/react-reconciler/src/ReactFiberWorkLoop.js
Labels: CLA Signed

#16681 fix typos on react-devtools comments
  packages/react-devtools-shared/src/backend/console.js
  packages/react-devtools-shared/src/backend/describeComponentFrame.js
  packages/react-devtools-shared/src/devtools/views/Components/NativeStyleEditor/AutoSizeInput.js
  packages/react-devtools-shared/src/devtools/views/Components/NativeStyleEditor/context.js
  packages/react-devtools-shared/src/devtools/views/DevTools.js
Labels: CLA Signed

#16684 Add FreshRuntime WWW bundle, remove ESLint
  scripts/rollup/bundles.js
Labels: CLA Signed

#16687 [Fresh] Fix a crash with implicit arrow return
  packages/react-refresh/src/ReactFreshBabelPlugin.js
  packages/react-refresh/src/__tests__/ReactFreshBabelPlugin-test.js
  packages/react-refresh/src/__tests__/__snapshots__/ReactFreshBabelPlugin-test.js.snap
Labels: CLA Signed

#16688 [Fresh] Add skipEnvCheck option to Babel plugin
  packages/react-refresh/src/ReactFreshBabelPlugin.js
  packages/react-refresh/src/__tests__/ReactFreshBabelPlugin-test.js
  packages/react-refresh/src/__tests__/ReactFreshIntegration-test.js
Labels: CLA Signed

#16695 Remove wrong copy-paste code in test
  packages/react-dom/src/__tests__/ReactDOMFiberAsync-test.internal.js
Labels: CLA Signed

#16693 [react-events] Keyboard: fix callback return types
  packages/react-events/src/dom/Keyboard.js
Labels: CLA Signed, React Flare

#16694 [react-events] Tap: change order of events
  packages/react-events/src/dom/Tap.js
  packages/react-events/src/dom/__tests__/Tap-test.internal.js
Labels: CLA Signed, React Flare

#16713 Schedule passive callbacks before layout effects are invoked
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactSchedulerIntegration-test.internal.js
Labels: CLA Signed

#16714 Let's schedule the passive effects even earlier
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactSchedulerIntegration-test.internal.js
Labels: CLA Signed

#16716 Remove console.log from copyWithSet
  packages/react-devtools-shared/src/backend/utils.js
Labels: CLA Signed

#16701 [DevTools] Fixed font family issue in Firefox.
  packages/react-devtools-shared/src/devtools/views/Tooltip.css
Labels: CLA Signed

#16730 [react-events] Remove stopPropagation (Press) + use document for delegation
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-events/src/dom/Press.js
  packages/react-events/src/dom/__tests__/Press-test.internal.js
Labels: CLA Signed, React Flare

#16738 [Fresh] Hash signatures
  packages/react-refresh/src/ReactFreshBabelPlugin.js
  packages/react-refresh/src/__tests__/ReactFreshBabelPlugin-test.js
Labels: CLA Signed

#16689 [react-events] Tap: add maximumDistance prop
  packages/react-events/src/dom/Tap.js
  packages/react-events/src/dom/__tests__/Tap-test.internal.js
  packages/react-events/src/dom/shared/index.js
Labels: CLA Signed, React Flare

#16708 Correct link for troubleshooting react-dev-tools (#16690)
  packages/react-devtools-extensions/popups/disabled.html
  packages/react-devtools/README.md
Labels: CLA Signed

#16617 [DevTools] [Context] Legacy Context
  packages/react-devtools-shared/src/__tests__/inspectedElementContext-test.js
  packages/react-devtools-shared/src/backend/legacy/renderer.js
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-devtools-shared/src/backend/types.js
  packages/react-devtools-shared/src/devtools/views/Components/InspectedElementContext.js
  packages/react-devtools-shared/src/devtools/views/Components/SelectedElement.js
  packages/react-devtools-shared/src/devtools/views/Components/types.js
Labels: CLA Signed

#16700 [DevTools] Support for adding props | Improved state/props value editing
  packages/react-devtools-shared/src/devtools/utils.js
  packages/react-devtools-shared/src/devtools/views/Components/EditableName.css
  packages/react-devtools-shared/src/devtools/views/Components/EditableName.js
  packages/react-devtools-shared/src/devtools/views/Components/EditableValue.css
  packages/react-devtools-shared/src/devtools/views/Components/EditableValue.js
  packages/react-devtools-shared/src/devtools/views/Components/InspectedElementTree.css
  packages/react-devtools-shared/src/devtools/views/Components/InspectedElementTree.js
  packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js
  packages/react-devtools-shared/src/devtools/views/Components/NativeStyleEditor/StyleEditor.js
  packages/react-devtools-shared/src/devtools/views/Components/SelectedElement.js
  packages/react-devtools-shared/src/devtools/views/hooks.js
Labels: CLA Signed

#16740 DevTools: Props editing interface tweaks
  packages/react-devtools-shared/src/devtools/views/Components/EditableValue.js
  packages/react-devtools-shared/src/devtools/views/Components/InspectedElementTree.css
  packages/react-devtools-shared/src/devtools/views/Components/InspectedElementTree.js
  packages/react-devtools-shared/src/devtools/views/Components/SelectedElement.js
Labels: CLA Signed

#16745 Handle SuspenseListComponent getting retried
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactSuspenseList-test.internal.js
Labels: CLA Signed

#16739 Mark root as already hydrated after committing
  packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
Labels: CLA Signed

#16743 Re-arrange slightly to prevent refactor hazard
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberExpirationTime.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberRoot.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/ReactUpdateQueue.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
  packages/react-reconciler/src/__tests__/__snapshots__/ReactIncrementalPerf-test.internal.js.snap
Labels: CLA Signed

#16732 [react-interactions] Add TabFocusContainer and TabbableScope UI components
  packages/react-dom/src/client/focus/TabFocusContainer.js
  packages/react-dom/src/client/focus/TabbableScope.js
  packages/react-dom/src/client/focus/__tests__/TabFocusContainer-test.internal.js
  packages/react-dom/src/client/focus/__tests__/TabbableScope-test.internal.js
  packages/react-events/src/dom/Keyboard.js
  packages/react-events/src/dom/testing-library/index.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/__tests__/ReactScope-test.internal.js
Labels: CLA Signed, React Flare

#16750 Change `trackedTouchCount` console.error to warn
  packages/legacy-events/ResponderEventPlugin.js
Labels: CLA Signed

#16748 [react-events] Use context.objectAssign in Tap responder
  packages/react-events/src/dom/Tap.js
Labels: CLA Signed, React Flare

#16757 [Scheduler][www] Put profiling feature behind flag
  packages/scheduler/src/forks/SchedulerFeatureFlags.www.js
Labels: CLA Signed

#16751 [react-interactions] More Tab Focus control handling
  packages/react-dom/src/client/focus/TabFocusContainer.js
  packages/react-dom/src/client/focus/TabFocusController.js
  packages/react-dom/src/client/focus/__tests__/TabFocusController-test.internal.js
  packages/react-events/src/dom/Keyboard.js
  packages/react-reconciler/src/ReactFiberScope.js
  packages/shared/ReactTypes.js
Labels: CLA Signed

#16766 [react-interactions] Add experimental FocusGrid API
  packages/react-dom/src/client/focus/FocusGrid.js
  packages/react-dom/src/client/focus/ReactTabFocus.js
  packages/react-dom/src/client/focus/TabbableScope.js
  packages/react-dom/src/client/focus/__tests__/FocusGrid-test.internal.js
  packages/react-events/src/dom/Keyboard.js
Labels: CLA Signed

#16776 Support disabling interaction tracing for suspense promises
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberThrow.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react/src/__tests__/ReactProfiler-test.internal.js
Labels: CLA Signed

#16771 Re-enable risky work loop changes
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberExpirationTime.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberRoot.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/ReactUpdateQueue.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspense-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
  packages/react-reconciler/src/__tests__/__snapshots__/ReactIncrementalPerf-test.internal.js.snap
Labels: CLA Signed

#16777 Remove unnecessary interaction tracing ping wrapper
  packages/react-reconciler/src/ReactFiberThrow.js
Labels: CLA Signed

#16779 [react-events] Keyboard calls preventDefault on 'click' events
  packages/react-events/src/dom/Keyboard.js
  packages/react-events/src/dom/__tests__/Keyboard-test.internal.js
  packages/react-events/src/dom/testing-library/domEvents.js
  packages/react-reconciler/src/__tests__/ReactScope-test.internal.js
Labels: CLA Signed, React Flare

#16781 [Scheduler] Prevent event log from growing unbounded
  packages/scheduler/src/SchedulerProfiling.js
  packages/scheduler/src/__tests__/SchedulerProfiling-test.js
  scripts/babel/transform-prevent-infinite-loops.js
  scripts/jest/preprocessor.js
Labels: CLA Signed

#16782 Spelling is fundamental
  packages/scheduler/src/SchedulerProfiling.js
  packages/scheduler/src/__tests__/SchedulerProfiling-test.js
Labels: CLA Signed

#16157 Add trusted types to react on client side
  .eslintrc.js
  packages/react-dom/src/client/DOMPropertyOperations.js
  packages/react-dom/src/client/ReactDOMComponent.js
  packages/react-dom/src/client/ToStringValue.js
  packages/react-dom/src/client/__tests__/trustedTypes-test.internal.js
  packages/react-dom/src/client/setAttribute.js
  packages/react-dom/src/client/setInnerHTML.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  scripts/rollup/validate/eslintrc.cjs.js
  scripts/rollup/validate/eslintrc.fb.js
  scripts/rollup/validate/eslintrc.rn.js
  scripts/rollup/validate/eslintrc.umd.js
Labels: CLA Signed

#16780 [react-events] Keyboard support for virtual clicks
  packages/react-events/src/dom/Keyboard.js
  packages/react-events/src/dom/__tests__/Keyboard-test.internal.js
  packages/react-events/src/dom/shared/index.js
Labels: CLA Signed, React Flare

#16795 Follow-up to initial Trusted Types support
  packages/react-dom/src/client/ToStringValue.js
  packages/react-dom/src/client/__tests__/trustedTypes-test.internal.js
  packages/react-dom/src/client/setInnerHTML.js
  scripts/flow/environment.js
Labels: CLA Signed

#16807 [react-core] Clear more properties in detachFiber
  packages/react-reconciler/src/ReactFiberCommitWork.js
Labels: CLA Signed

#16806 [react-ui] FocusGrid -> ReactFocusTable + tweaks and fixes
  packages/react-reconciler/src/ReactFiberScope.js
  packages/react-ui/accessibility/src/FocusGrid.js
  packages/react-ui/accessibility/src/ReactFocusTable.js
  packages/react-ui/accessibility/src/__tests__/FocusGrid-test.internal.js
  packages/react-ui/accessibility/src/__tests__/ReactFocusTable-test.internal.js
  packages/shared/ReactTypes.js
Labels: CLA Signed

#16809 [scheduler][profiler] Start time of delayed tasks
  packages/scheduler/src/Scheduler.js
  packages/scheduler/src/__tests__/SchedulerProfiling-test.js
Labels: CLA Signed

#16804 [react-a11y] Add react-ui/accessibility to bundle build
  packages/react-ui/accessibility/focus-table.js
  packages/react-ui/accessibility/src/FocusTable.js
  packages/react-ui/accessibility/src/TabFocus.js
  packages/react-ui/accessibility/src/__tests__/FocusTable-test.internal.js
  packages/react-ui/accessibility/src/__tests__/TabFocus-test.internal.js
  packages/react-ui/accessibility/tab-focus.js
  packages/react-ui/accessibility/tabbable-scope.js
  scripts/rollup/build.js
  scripts/rollup/bundles.js
Labels: CLA Signed

#16811 [react-ui] Fix bundle name [hotfix]
  scripts/rollup/bundles.js
Labels: CLA Signed

#16810 Release script filters DevTools NPM packages
  scripts/release/utils.js
Labels: CLA Signed

#16798 [react-devtools-shared] Added string type check for object name prop in getDisplayName function
  packages/react-devtools-shared/src/__tests__/utils-test.js
  packages/react-devtools-shared/src/utils.js
Labels: CLA Signed

#16212 Optimize objectIs
  packages/shared/objectIs.js
Labels: CLA Signed

#16820 [react-core] Do not null fiber.sibling in detachFiber
  packages/react-reconciler/src/ReactFiberCommitWork.js
Labels: CLA Signed

#16821 [React Native] Fix for view config registrations
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativeViewConfigRegistry.js
  packages/react-native-renderer/src/__tests__/ReactNativeEvents-test.internal.js
  scripts/rollup/shims/react-native/ReactNativeViewConfigRegistry.js
Labels: CLA Signed

#16823 [Fresh] Always remount classes
  packages/react-reconciler/src/ReactFiberHotReloading.js
  packages/react-refresh/src/__tests__/ReactFreshIntegration-test.js
Labels: CLA Signed

#16578 prevent firefox marking required textareas invalid
  fixtures/dom/src/components/fixtures/textareas/index.js
  packages/react-dom/src/__tests__/ReactDOMTextarea-test.js
  packages/react-dom/src/client/ReactDOMTextarea.js
Labels: CLA Signed

#16822 [react-ui] Remove event object warnings
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
Labels: Browser: IE, CLA Signed, React Flare

#16834 [DevTools] Remove Welcome dialog
  packages/react-devtools-core/src/standalone.js
  packages/react-devtools-extensions/src/main.js
  packages/react-devtools-shared/src/devtools/views/DevTools.js
  packages/react-devtools-shared/src/devtools/views/ShowWelcomeToTheNewDevToolsDialog.css
  packages/react-devtools-shared/src/devtools/views/ShowWelcomeToTheNewDevToolsDialog.js
  packages/react-devtools-shell/src/devtools.js
Labels: CLA Signed

#16827 [react-ui/events] Tap responder API changes
  packages/react-ui/events/src/dom/Press.js
  packages/react-ui/events/src/dom/Tap.js
  packages/react-ui/events/src/dom/__tests__/Press-test.internal.js
  packages/react-ui/events/src/dom/__tests__/PressLegacy-test.internal.js
  packages/react-ui/events/src/dom/__tests__/Tap-test.internal.js
  packages/react-ui/events/src/dom/shared/index.js
  packages/react-ui/events/src/dom/testing-library/domEnvironment.js
Labels: CLA Signed, React Flare

#16737 Exclude react-dom when flow checking other builds
  scripts/flow/config/flowconfig
  scripts/flow/createFlowConfigs.js
Labels: CLA Signed

#16833 [react-ui] Add preventDefault+ to Keyboard + update a11y components
  packages/react-ui/accessibility/src/FocusTable.js
  packages/react-ui/accessibility/src/TabFocus.js
  packages/react-ui/accessibility/src/__tests__/TabFocus-test.internal.js
  packages/react-ui/events/src/dom/Keyboard.js
  packages/react-ui/events/src/dom/Press.js
  packages/react-ui/events/src/dom/__tests__/Keyboard-test.internal.js
Labels: CLA Signed, React Flare

#16860 [react-interactions] Fix typo in FocusTable
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
Labels: CLA Signed

#16862 [react-interaction] Tweak Focus Table component
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-reconciler/src/ReactFiber.js
Labels: CLA Signed

#16837 [react-ui] Improve consistency of Tap responder
  packages/react-interactions/events/src/dom/Tap.js
  packages/react-interactions/events/src/dom/__tests__/Tap-test.internal.js
Labels: CLA Signed, React Flare

#16865 [work loop] Prevent work loop from being inlined
  packages/react-reconciler/src/ReactFiberWorkLoop.js
Labels: CLA Signed

#16725 Event Replaying
  packages/legacy-events/EventPluginHub.js
  packages/legacy-events/EventSystemFlags.js
  packages/legacy-events/PluginModuleType.js
  packages/legacy-events/ResponderEventPlugin.js
  packages/legacy-events/__tests__/ResponderEventPlugin-test.internal.js
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMComponentTree.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/events/BeforeInputEventPlugin.js
  packages/react-dom/src/events/ChangeEventPlugin.js
  packages/react-dom/src/events/EnterLeaveEventPlugin.js
  packages/react-dom/src/events/ReactBrowserEventEmitter.js
  packages/react-dom/src/events/ReactDOMEventListener.js
  packages/react-dom/src/events/ReactDOMEventReplaying.js
  packages/react-dom/src/events/SelectEventPlugin.js
  packages/react-dom/src/events/SimpleEventPlugin.js
  packages/react-native-renderer/src/ReactFabricEventEmitter.js
  packages/react-native-renderer/src/ReactNativeBridgeEventPlugin.js
  packages/react-native-renderer/src/ReactNativeEventEmitter.js
  packages/react-reconciler/src/ReactFiberCommitWork.js
  packages/react-reconciler/src/ReactFiberTreeReflection.js
  packages/react-reconciler/src/forks/ReactFiberHostConfig.custom.js
  packages/shared/HostConfigWithNoHydration.js
Labels: CLA Signed

#16801 [suspense][error handling] Inline renderRoot and fix error handling bug
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#16868 [react-interactions] Add no-op stopPropagation + preventDefault to Press
  packages/react-interactions/events/src/dom/Press.js
  packages/react-interactions/events/src/dom/PressLegacy.js
Labels: CLA Signed, React Flare

#16866 [react-interaction] Refactor a11y components more
  packages/react-interactions/accessibility/focus-control.js
  packages/react-interactions/accessibility/src/FocusControl.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/TabFocus.js
  packages/react-interactions/accessibility/src/TabbableScope.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/TabFocus-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/TabbableScope-test.internal.js
  scripts/rollup/bundles.js
Labels: CLA Signed, React Flare

#16867 Fix DevTools v4.1 editable hook regression
  packages/react-devtools-shared/src/devtools/views/Components/EditableValue.js
  packages/react-devtools-shared/src/devtools/views/Components/HooksTree.js
  packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js
  packages/react-devtools-shared/src/devtools/views/hooks.js
Labels: CLA Signed

#16864 Revert change to backend injection method from PR #16752
  packages/react-devtools-extensions/src/inject.js
  packages/react-devtools-extensions/src/injectGlobalHook.js
  packages/react-devtools-extensions/src/main.js
Labels: CLA Signed

#16870 [react-interactions] Press with useRef instead of useState
  packages/react-interactions/events/src/dom/Press.js
  packages/react-interactions/events/src/dom/testing-library/domEvents.js
Labels: CLA Signed, React Flare

#16871 Idle updates should not be blocked by hidden work
  packages/react-reconciler/src/ReactFiberExpirationTime.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactSchedulerIntegration-test.internal.js
  packages/react/src/__tests__/ReactDOMTracing-test.internal.js
  scripts/jest/matchers/schedulerTestMatchers.js
Labels: CLA Signed

#16799 Warning system refactoring (part 1)
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/server/ReactPartialRenderer.js
  packages/react-dom/src/test-utils/ReactTestUtils.js
  packages/react-is/src/ReactIs.js
  packages/react-reconciler/src/ReactStrictModeWarnings.js
  packages/react/src/ReactBaseClasses.js
  packages/react/src/ReactElementValidator.js
  packages/shared/forks/lowPriorityWarningWithoutStack.www.js
  packages/shared/lowPriorityWarning.js
  packages/shared/lowPriorityWarningWithoutStack.js
  scripts/jest/matchers/__tests__/toWarnDev-test.js
  scripts/print-warnings/print-warnings.js
  scripts/rollup/forks.js
Labels: CLA Signed

#16875 [react-interactions] Add FocusList component
  packages/react-interactions/accessibility/src/FocusList.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/__tests__/FocusList-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
Labels: CLA Signed

#16876 [react-interactions] Make FocusList bundle
  packages/react-interactions/accessibility/focus-list.js
  packages/react-interactions/accessibility/src/FocusList.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/TabbableScope.js
  packages/react-interactions/accessibility/src/__tests__/FocusList-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
  scripts/rollup/bundles.js
Labels: CLA Signed

#16874 [react-interactions] TabFocus -> FocusManager
  packages/react-interactions/accessibility/focus-manager.js
  packages/react-interactions/accessibility/src/FocusManager.js
  packages/react-interactions/accessibility/src/TabFocus.js
  packages/react-interactions/accessibility/src/__tests__/FocusManager-test.internal.js
  packages/react-interactions/events/src/dom/Focus.js
  scripts/rollup/bundles.js
Labels: CLA Signed, React Flare

#16879 [React Native] Improve errors for invalid ViewConfig getter functions
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativeViewConfigRegistry.js
  packages/react-native-renderer/src/__tests__/ReactNativeError-test.internal.js
  scripts/rollup/shims/react-native/ReactNativeViewConfigRegistry.js
Labels: CLA Signed

#16892 [react-interactions] Add initial docs explaining React Scopes
  packages/react-interactions/accessibility/README.md
  packages/react-interactions/events/README.md
Labels: CLA Signed

#16889 [react-interactions] Add Portal propagation configuration
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/__tests__/DOMEventResponderSystem-test.internal.js
  packages/react-interactions/events/src/dom/Focus.js
  packages/react-interactions/events/src/dom/Keyboard.js
  packages/shared/ReactTypes.js
  packages/shared/createEventResponder.js
Labels: CLA Signed, React Flare

#16883 These flags are hard coded in our internal config
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed

#16881 Include tag in begin/complete invariant
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberCompleteWork.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#16894 [react-interactions] Add more documentation for a11y components
  packages/react-interactions/accessibility/docs/FocusControl.md
  packages/react-interactions/accessibility/docs/FocusManager.md
  packages/react-interactions/accessibility/docs/TabbableScope.md
  packages/react-interactions/accessibility/src/FocusControl.js
  packages/react-interactions/accessibility/src/__tests__/FocusManager-test.internal.js
Labels: CLA Signed

#16893 [devtools] Add support for React Scope symbol/number
  packages/react-devtools-shared/src/backend/renderer.js
Labels: CLA Signed

#16878 Update useEditableValue hook to sync external value changes
  packages/react-devtools-shared/src/__tests__/useEditableValue-test.js
  packages/react-devtools-shared/src/devtools/views/Components/EditableValue.js
  packages/react-devtools-shared/src/devtools/views/Components/HooksTree.js
  packages/react-devtools-shared/src/devtools/views/Components/InspectedElementTree.js
  packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js
  packages/react-devtools-shared/src/devtools/views/Components/TreeContext.js
  packages/react-devtools-shared/src/devtools/views/hooks.js
  packages/react-devtools/CHANGELOG.md
Labels: CLA Signed

#16895 [react-interactions] FocusTable nesting fix
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
Labels: CLA Signed

#16880 Selective Hydration
  packages/react-dom/src/__tests__/ReactDOMServerSelectiveHydration-test.internal.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMComponentTree.js
  packages/react-dom/src/events/ReactDOMEventReplaying.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed

#16900 Moving backend injection to the content script
  packages/react-devtools-extensions/src/inject.js
  packages/react-devtools-extensions/src/injectGlobalHook.js
  packages/react-devtools-extensions/src/main.js
Labels: CLA Signed

#16903 [react-interactions] Add wrapping support to FocusList/FocusTable
  packages/react-interactions/accessibility/src/FocusList.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/__tests__/FocusList-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
Labels: CLA Signed

#16897 DevTools shows unsupported renderer version dialog
  packages/react-devtools-extensions/src/main.js
  packages/react-devtools-shared/src/backend/agent.js
  packages/react-devtools-shared/src/backend/index.js
  packages/react-devtools-shared/src/backend/types.js
  packages/react-devtools-shared/src/bridge.js
  packages/react-devtools-shared/src/constants.js
  packages/react-devtools-shared/src/devtools/store.js
  packages/react-devtools-shared/src/devtools/views/DevTools.js
  packages/react-devtools-shared/src/devtools/views/UnsupportedVersionDialog.css
  packages/react-devtools-shared/src/devtools/views/UnsupportedVersionDialog.js
  packages/react-devtools-shell/src/devtools.js
  packages/react-devtools/CHANGELOG.md
Labels: CLA Signed

#16907 [bugfix] Fix false positive render phase update
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.internal.js
Labels: CLA Signed

#16898 Add HostComponent type to ReactNative
  packages/react-native-renderer/src/NativeMethodsMixin.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeComponent.js
  packages/react-native-renderer/src/ReactNativeFiberHostComponent.js
  packages/react-native-renderer/src/ReactNativeTypes.js
Labels: CLA Signed

#16909 expose isHydrating
  packages/react-dom/src/client/ReactDOMFB.js
  packages/react-reconciler/src/ReactFiberHydrationContext.js
Labels: CLA Signed

#16915 [react-interactions] Fix virtual click heuristic
  packages/react-interactions/events/src/dom/shared/index.js
Labels: CLA Signed, React Flare

#16934 Fixed useEditableValue() to safely compare values like NaN
  packages/react-devtools-shared/src/__tests__/useEditableValue-test.js
  packages/react-devtools-shared/src/devtools/views/hooks.js
Labels: CLA Signed

#16935 [Selective Hydration] Increase priority for non-synchronous discrete events and retries
  packages/react-dom/src/__tests__/ReactDOMServerSelectiveHydration-test.internal.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/events/ReactDOMEventReplaying.js
  packages/react-reconciler/src/ReactFiberReconciler.js
Labels: CLA Signed

#16882 Remove enableUserBlockingEvents flag
  packages/react-dom/src/events/DOMEventResponderSystem.js
  packages/react-dom/src/events/ReactDOMEventListener.js
  packages/react-dom/src/events/__tests__/ChangeEventPlugin-test.internal.js
  packages/react-interactions/events/src/dom/__tests__/Hover-test.internal.js
  packages/react-interactions/events/src/dom/__tests__/Input-test.internal.js
  packages/react-interactions/events/src/dom/__tests__/MixedResponders-test-internal.js
  packages/react-native-renderer/src/ReactFabricEventResponderSystem.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed

#16943 Allow Suspense Mismatch on the Client to Silently Proceed
  packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js
  packages/react-reconciler/src/ReactFiberHydrationContext.js
Labels: CLA Signed

#16949 updated comment message with better wording
  packages/react/src/ReactElement.js
Labels: CLA Signed

#16922 [react-interactins] FocusTable tabScope handling+tabIndex control
  packages/react-interactions/accessibility/src/FocusControl.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
  scripts/rollup/bundles.js
Labels: CLA Signed

#16958 [react-interactions] Add tab handling to FocusList
  packages/react-interactions/accessibility/src/FocusList.js
  packages/react-interactions/accessibility/src/FocusManager.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/__tests__/FocusList-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
  packages/react-interactions/events/src/dom/testing-library/index.js
  scripts/rollup/bundles.js
Labels: CLA Signed

#16953 [DevTools] targetOrigin of postMessage needs to be '*' for local files
  packages/react-devtools-extensions/src/main.js
Labels: CLA Signed

#16963 Remove IIFE wrappers from dev invariant checks
  scripts/error-codes/__tests__/__snapshots__/transform-error-messages.js.snap
  scripts/error-codes/__tests__/transform-error-messages.js
  scripts/error-codes/transform-error-messages.js
Labels: CLA Signed
