Repository facebook/react, pull requests merged in 2020-01, with the labels that each got.

#17746 Build and store DevTools artifacts in Circle CI
  .circleci/config.yml
  scripts/circleci/pack_and_store_devtools_artifacts.sh
Labels: CLA Signed

#17757 Added missing guard to DevTools for Objects with null proto
  packages/react-devtools-shared/src/__tests__/__snapshots__/inspectedElementContext-test.js.snap
  packages/react-devtools-shared/src/__tests__/inspectedElementContext-test.js
  packages/react-devtools-shared/src/__tests__/legacy/__snapshots__/inspectElement-test.js.snap
  packages/react-devtools-shared/src/__tests__/legacy/inspectElement-test.js
  packages/react-devtools-shared/src/utils.js
  packages/react-devtools-shell/src/app/InspectableElements/UnserializableProps.js
Labels: CLA Signed

#17758 Fixed CircleCI DevTools build artifact tar internal structure
  scripts/circleci/pack_and_store_devtools_artifacts.sh
Labels: CLA Signed

#17760 DevTools Profiler commit selector wraps around
  packages/react-devtools-shared/src/devtools/views/Profiler/SnapshotSelector.js
Labels: CLA Signed

#17759 Partial fix DevTools Profiler "Could not find node…" error
  packages/react-devtools-shared/src/__tests__/profilerStore-test.js
  packages/react-devtools-shared/src/backend/renderer.js
Labels: CLA Signed

#17768 DevTools: Replaced unsafe hasOwnProperty() calls
  packages/react-devtools-shared/src/__tests__/__snapshots__/inspectedElementContext-test.js.snap
  packages/react-devtools-shared/src/__tests__/inspectedElementContext-test.js
  packages/react-devtools-shared/src/__tests__/legacy/__snapshots__/inspectElement-test.js.snap
  packages/react-devtools-shared/src/__tests__/legacy/inspectElement-test.js
  packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js
  packages/react-devtools-shared/src/devtools/views/utils.js
  packages/react-devtools-shared/src/utils.js
  packages/react-devtools-shell/src/app/InspectableElements/EdgeCaseObjects.js
  packages/react-devtools-shell/src/app/InspectableElements/InspectableElements.js
  packages/react-devtools-shell/src/app/InspectableElements/UnserializableProps.js
Labels: CLA Signed

#17538 HostText needs to copy over from current if it is unchanged
  packages/react-reconciler/src/ReactFiberCompleteWork.js
Labels: CLA Signed

#17773 Remove toString of dangerouslySetInnerHTML
  packages/react-dom/src/client/ReactDOMComponent.js
Labels: CLA Signed

#17771 DevTools Profiler: Improve how empty commits are filtered
  packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-devtools-shared/src/devtools/views/Profiler/utils.js
Labels: CLA Signed

#17789 DevTools: Improve function props display for inspected elements
  packages/react-devtools-shared/src/__tests__/__snapshots__/inspectedElementContext-test.js.snap
  packages/react-devtools-shared/src/__tests__/inspectedElementContext-test.js
  packages/react-devtools-shared/src/__tests__/legacy/__snapshots__/inspectElement-test.js.snap
  packages/react-devtools-shared/src/__tests__/legacy/inspectElement-test.js
  packages/react-devtools-shared/src/hydration.js
  packages/react-devtools-shared/src/utils.js
  packages/react-devtools-shell/src/app/InspectableElements/SimpleValues.js
Labels: CLA Signed

#17790 Renamed "backend.js" to "react_devtools_backend.js"
  packages/react-devtools-extensions/chrome/manifest.json
  packages/react-devtools-extensions/firefox/manifest.json
  packages/react-devtools-extensions/src/injectGlobalHook.js
  packages/react-devtools-extensions/webpack.backend.js
Labels: CLA Signed

#17775 Scope dev tools wildcard styles within DevTools CSS class
  packages/react-devtools-shared/src/devtools/views/DevTools.css
  packages/react-devtools-shared/src/devtools/views/root.css
Labels: CLA Signed

#17765 [react-interactions] Fix Hover issues with portals
  packages/react-interactions/events/src/dom/Hover.js
  packages/react-interactions/events/src/dom/__tests__/Hover-test.internal.js
Labels: CLA Signed

#17797 Renamed "ReactDOM-fb" imports to "ReactDOM" in www shims
  scripts/rollup/shims/facebook-www/ReactBrowserEventEmitter_DO_NOT_USE.js
  scripts/rollup/shims/facebook-www/ReactDOMComponentTree_DO_NOT_USE.js
  scripts/rollup/shims/facebook-www/ReactInstanceMap_DO_NOT_USE.js
  scripts/rollup/shims/facebook-www/findDOMNode.js
  scripts/rollup/shims/facebook-www/renderSubtreeIntoContainer_DO_NOT_USE.js
Labels: CLA Signed

#17799 Revert "Revert "Dispatch commands to both UIManagers from both renderers (#17211)" (#17232)"
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-native-renderer/src/__tests__/ReactFabricAndNative-test.internal.js
Labels: CLA Signed

#17806 Add configuration for the "Stale" GitHub App
  .github/stale.yml
Labels: CLA Signed, React Core Team

#17816 Add better test coverage for hooks in DevTools Profiler's change-detection
  packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap
  packages/react-devtools-shared/src/__tests__/profilingCache-test.js
Labels: CLA Signed, React Core Team

#16982 Update create-react-app note
  packages/eslint-plugin-react-hooks/README.md
Labels: CLA Signed, Resolution: Stale

#15784 Create SECURITY.md
  SECURITY.md
Labels: CLA Signed, Resolution: Stale

#17039 Fix a typo in printOperationsArray function
  packages/react-devtools-shared/src/utils.js
Labels: CLA Signed, Resolution: Stale

#17034 Fix typo in ReactSuspenseList-test.internal.js
  packages/react-reconciler/src/__tests__/ReactSuspenseList-test.internal.js
Labels: CLA Signed, Resolution: Stale

#17815 Add GitHub issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA Signed, React Core Team

#16164 Create ReactFabric.stopSurface and use that for bridgeless mode binding
  packages/react-native-renderer/src/ReactFabric.js
  scripts/rollup/shims/react-native/ReactFabric.js
Labels: CLA Signed, Resolution: Stale

#17817 Fix issue template for questions
  .github/ISSUE_TEMPLATE/question.md
Labels: CLA Signed, React Core Team

#17824 [Fresh] Fix edge case with early function call
  packages/react-refresh/src/ReactFreshRuntime.js
  packages/react-refresh/src/__tests__/ReactFreshIntegration-test.js
Labels: CLA Signed, React Core Team

#17829 Update babel-eslint and eslint packages
  .eslintrc.js
  package.json
  scripts/eslint/index.js
  yarn.lock
Labels: CLA Signed, React Core Team

#17839 Update typescript package and jest preprocessor
  package.json
  scripts/jest/typescript/preprocessor.js
  yarn.lock
Labels: CLA Signed, React Core Team

#17838 Re-enabled DevTools context menu option in Firefox
  packages/react-devtools-extensions/firefox/build.js
  packages/react-devtools-extensions/src/main.js
Labels: CLA Signed, React Core Team

#17837 Add support for Node v13 for development
  package.json
Labels: CLA Signed

#17841 Removed 'reactInternal' reference in DevTools overlay highlighter
  packages/react-devtools-shared/src/backend/legacy/renderer.js
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-devtools-shared/src/backend/types.js
  packages/react-devtools-shared/src/backend/views/Highlighter/Overlay.js
Labels: CLA Signed, React Core Team

#17835 [react-interactions] Add DO_NOT_USE to Scope methods
  packages/react-interactions/accessibility/README.md
  packages/react-interactions/accessibility/docs/TabbableScopeQuery.md
  packages/react-interactions/accessibility/src/FocusContain.js
  packages/react-interactions/accessibility/src/FocusGroup.js
  packages/react-interactions/accessibility/src/FocusManager.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/__tests__/TabbableScopeQuery-test.internal.js
  packages/react-interactions/accessibility/src/shared/getTabbableNodes.js
  packages/react-reconciler/src/ReactFiberScope.js
  packages/react-reconciler/src/__tests__/ReactScope-test.internal.js
  packages/shared/ReactTypes.js
Labels: CLA Signed, React Core Team

#17849 Fix DevTools Flow error for key-sort function
  packages/react-devtools-shared/src/utils.js
Labels: CLA Signed, React Core Team

#17859 [react-interactions] Remove deprecated Scope APIs + update Focus components
  packages/react-interactions/accessibility/README.md
  packages/react-interactions/accessibility/docs/FocusContain.md
  packages/react-interactions/accessibility/docs/FocusManager.md
  packages/react-interactions/accessibility/docs/TabbableScopeQuery.md
  packages/react-interactions/accessibility/focus-contain.js
  packages/react-interactions/accessibility/focus-group.js
  packages/react-interactions/accessibility/focus-manager.js
  packages/react-interactions/accessibility/focus-table.js
  packages/react-interactions/accessibility/src/FocusContain.js
  packages/react-interactions/accessibility/src/FocusGroup.js
  packages/react-interactions/accessibility/src/FocusManager.js
  packages/react-interactions/accessibility/src/FocusTable.js
  packages/react-interactions/accessibility/src/TabbableScopeQuery.js
  packages/react-interactions/accessibility/src/__tests__/FocusContain-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/FocusGroup-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/FocusManager-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/FocusTable-test.internal.js
  packages/react-interactions/accessibility/src/__tests__/TabbableScopeQuery-test.internal.js
  packages/react-interactions/accessibility/src/shared/emulateBrowserTab.js
  packages/react-interactions/accessibility/src/shared/getTabbableNodes.js
  packages/react-interactions/accessibility/src/shared/setElementCanTab.js
  packages/react-interactions/accessibility/tabbable-scope-query.js
  packages/react-reconciler/src/ReactFiberScope.js
  packages/react-reconciler/src/__tests__/ReactScope-test.internal.js
  packages/shared/ReactTypes.js
Labels: CLA Signed, React Core Team

#17861 Remove ReactInstanceMap_DO_NOT_USE shim
  scripts/rollup/shims/facebook-www/ReactInstanceMap_DO_NOT_USE.js
Labels: CLA Signed, React Core Team

#17122 fix #17121
  package.json
Labels: CLA Signed, Resolution: Stale

#17625 Remove renderPhaseUpdates Map
  packages/react-reconciler/src/ReactFiberBeginWork.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.internal.js
Labels: CLA Signed, React Core Team

#17873 Add feature flag around React.createFactory
  packages/react-is/src/__tests__/ReactIs-test.js
  packages/react/src/React.js
  packages/react/src/__tests__/ReactCoffeeScriptClass-test.coffee
  packages/react/src/__tests__/ReactElement-test.js
  packages/react/src/__tests__/ReactElementClone-test.js
  packages/react/src/__tests__/ReactElementJSX-test.internal.js
  packages/react/src/__tests__/ReactElementValidator-test.internal.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#17874 Add disable <textarea/> children flag
  packages/react-dom/src/__tests__/ReactDOMTextarea-test.js
  packages/react-dom/src/client/ReactDOMTextarea.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#17875 Remove FB specific React isomorphic build
  packages/react/index.fb.js
  packages/react/src/ReactFB.js
Labels: CLA Signed, React Core Team

#17878 Add React.createFactory() deprecation warning
  packages/react-is/src/__tests__/ReactIs-test.js
  packages/react/src/ReactElementValidator.js
  packages/react/src/__tests__/ReactElement-test.js
  packages/react/src/__tests__/ReactElementJSX-test.internal.js
  packages/react/src/__tests__/ReactElementValidator-test.internal.js
Labels: CLA Signed, React Core Team

#17880 Add unstable_renderSubtreeIntoContainer and unstable_createPortal feature flags
  packages/react-dom/src/__tests__/ReactDOMFiber-test.js
  packages/react-dom/src/__tests__/renderSubtreeIntoContainer-test.js
  packages/react-dom/src/client/ReactDOM.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  scripts/flow/config/flowconfig
Labels: CLA Signed, React Core Team

#17888 Remove dynamic GKs for selective/train
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#17842 Update to flow-bin@0.89
  package.json
  packages/react-cache/src/LRU.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-interactions/events/src/dom/PressLegacy.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeHostConfig.js
  packages/react-test-renderer/src/ReactTestHostConfig.js
  packages/react/src/ReactHooks.js
  scripts/flow/config/flowconfig
  scripts/flow/environment.js
  yarn.lock
Labels: CLA Signed, React Core Team

#17864 Add different string ref warning when owner and self are different
  packages/react-dom/src/__tests__/ReactDeprecationWarnings-test.internal.js
  packages/react-reconciler/src/ReactChildFiber.js
  packages/react/src/ReactElement.js
Labels: CLA Signed, React Core Team

#17897 chore: update to latest release of babel
  package.json
  packages/babel-plugin-react-jsx/__tests__/TransformJSXToReactCreateElement-test.js
  packages/babel-plugin-react-jsx/__tests__/TransformJSXToReactJSX-test.js
  yarn.lock
Labels: CLA Signed

#17901 Update various monorepo dependencies
  package.json
  yarn.lock
Labels: CLA Signed, React Core Team

#17907 Remove unused modules from legacy event responders
  packages/react-interactions/events/drag.js
  packages/react-interactions/events/scroll.js
  packages/react-interactions/events/src/dom/Drag.js
  packages/react-interactions/events/src/dom/Scroll.js
  packages/react-interactions/events/src/dom/Swipe.js
  packages/react-interactions/events/src/dom/__tests__/Drag-test.internal.js
  packages/react-interactions/events/src/dom/__tests__/Scroll-test.internal.js
  packages/react-interactions/events/swipe.js
  packages/react-interactions/package.json
  scripts/rollup/bundles.js
Labels: CLA Signed, React Core Team

#17892 Update to flow 0.97
  package.json
  packages/react-debug-tools/src/ReactDebugHooks.js
  packages/react-dom/src/server/ReactPartialRendererHooks.js
  packages/react-reconciler/src/ReactFiberHooks.js
  packages/react-test-renderer/src/ReactShallowRenderer.js
  packages/shared/getComponentName.js
  packages/shared/objectIs.js
  scripts/flow/config/flowconfig
  yarn.lock
Labels: CLA Signed, React Core Team

#17896 chore: upgrade to jest 25
  fixtures/dom/package.json
  fixtures/dom/yarn.lock
  package.json
  packages/jest-mock-scheduler/package.json
  packages/jest-react/package.json
  packages/react-dom/src/__tests__/CSSPropertyOperations-test.js
  packages/react-dom/src/__tests__/ReactDOMComponent-test.js
  packages/react-dom/src/__tests__/ReactDOMInput-test.js
  packages/react-dom/src/__tests__/ReactDOMSelect-test.js
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationUserInteraction-test.js
  packages/react-dom/src/events/__tests__/ChangeEventPlugin-test.internal.js
  packages/react-dom/src/events/__tests__/DeprecatedDOMEventResponderSystem-test.internal.js
  packages/react-dom/src/events/__tests__/SelectEventPlugin-test.js
  packages/react-interactions/events/src/dom/__tests__/Input-test.internal.js
  scripts/jest/config.base.js
  yarn.lock
Labels: CLA Signed

#17916 Removed Root API callback params and added warnings
  packages/react-dom/src/__tests__/ReactDOMRoot-test.js
  packages/react-dom/src/client/ReactDOMLegacy.js
  packages/react-dom/src/client/ReactDOMRoot.js
Labels: CLA Signed, React Core Team

#17914 [Concurrent Mode] Add missing event plugin priorities
  packages/react-dom/src/events/DOMEventProperties.js
Labels: CLA Signed, React Core Team

#17919 Add semver dependency explicitly to DevTools
  packages/react-devtools-shared/package.json
Labels: CLA Signed, React Core Team

#17922 Show first component stack in context warning
  packages/react-reconciler/src/ReactStrictModeWarnings.js
  packages/react-reconciler/src/__tests__/ReactIncremental-test.internal.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js
  packages/react-reconciler/src/__tests__/ReactIncrementalPerf-test.internal.js
  packages/react-reconciler/src/__tests__/ReactNewContext-test.internal.js
  packages/react/src/__tests__/ReactStrictMode-test.js
Labels: CLA Signed, React Core Team

#17923 Use next tag for canary releases in the doc
  scripts/release/README.md
Labels: CLA Signed, React Core Team

#17926 Bugfix: Expiring a partially completed tree
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js
  packages/react-reconciler/src/__tests__/ReactIncrementalUpdates-test.internal.js
Labels: CLA Signed, React Core Team

#17936 Add ReactDOM.unstable_renderSubtreeIntoContainer warning flag
  packages/react-dom/src/__tests__/renderSubtreeIntoContainer-test.js
  packages/react-dom/src/client/ReactDOM.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.persistent.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#17937 Ensure createRoot warning parity with ReactDOM.render
  packages/react-dom/src/__tests__/ReactDOMRoot-test.js
  packages/react-dom/src/client/ReactDOMRoot.js
Labels: CLA Signed, React Core Team

#17933 Fix Event Replaying in Flare by Eagerly Adding Active Listeners
  packages/react-dom/src/__tests__/ReactDOMServerSelectiveHydration-test.internal.js
  packages/react-dom/src/events/ReactDOMEventReplaying.js
Labels: CLA Signed, React Core Team

#17939 Remove root.unmount() callback from DevTools code
  packages/react-devtools-extensions/src/main.js
Labels: CLA Signed, React Core Team

#17941 Revert "Bugfix: Expiring a partially completed tree (#17926)"
  packages/react-reconciler/src/ReactFiberWorkLoop.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js
  packages/react-reconciler/src/__tests__/ReactIncrementalUpdates-test.internal.js
Labels: CLA Signed, React Core Team

#17942 StrictMode should call sCU twice in DEV
  packages/react-reconciler/src/ReactFiberClassComponent.js
  packages/react/src/__tests__/ReactStrictMode-test.js
Labels: CLA Signed, React Core Team

#17902 Update google-closure-compiler
  package.json
  yarn.lock
Labels: CLA Signed, React Core Team

#17931 fix: BigInt serialize issue in devtools copy to clipboard
  packages/react-devtools-shared/src/backend/utils.js
  packages/react-devtools-shell/src/app/InspectableElements/UnserializableProps.js
Labels: CLA Signed

#17946 Typo fix
  packages/react-dom/src/events/ReactDOMEventReplaying.js
Labels: CLA Signed

#17948 Add DevTools tests for copying complex values
  packages/react-devtools-shared/src/__tests__/inspectedElementContext-test.js
  packages/react-devtools-shared/src/__tests__/legacy/inspectElement-test.js
Labels: CLA Signed, React Core Team
