Repository facebook/react, pull requests merged in 2021-11, with the labels that each got.

#22665 Pin CI to Node 14
  .circleci/config.yml
Labels: CLA Signed, React Core Team

#22664 Re-land #22292 (Remove useMutableSource from open source build)
  packages/react-debug-tools/src/__tests__/ReactHooksInspectionIntegration-test.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/__tests__/useMutableSource-test.internal.js
  packages/react-reconciler/src/__tests__/useMutableSourceHydration-test.js
  packages/react/index.experimental.js
  packages/react/index.stable.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#22644 useId
  packages/react-debug-tools/src/ReactDebugHooks.js
  packages/react-debug-tools/src/__tests__/ReactHooksInspectionIntegration-test.js
  packages/react-dom/src/__tests__/ReactDOMUseId-test.js
  packages/react-dom/src/server/ReactPartialRendererHooks.js
  packages/react-reconciler/src/ReactChildFiber.new.js
  packages/react-reconciler/src/ReactChildFiber.old.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberFlags.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberHydrationContext.new.js
  packages/react-reconciler/src/ReactFiberHydrationContext.old.js
  packages/react-reconciler/src/ReactFiberLane.new.js
  packages/react-reconciler/src/ReactFiberLane.old.js
  packages/react-reconciler/src/ReactFiberSuspenseComponent.new.js
  packages/react-reconciler/src/ReactFiberSuspenseComponent.old.js
  packages/react-reconciler/src/ReactFiberTreeContext.new.js
  packages/react-reconciler/src/ReactFiberTreeContext.old.js
  packages/react-reconciler/src/ReactFiberUnwindWork.new.js
  packages/react-reconciler/src/ReactFiberUnwindWork.old.js
  packages/react-reconciler/src/ReactInternalTypes.js
  packages/react-reconciler/src/clz32.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFizzServer.js
  packages/react-server/src/ReactFizzTreeContext.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-suspense-test-utils/src/ReactSuspenseTestUtils.js
  packages/react/index.classic.fb.js
  packages/react/index.experimental.js
  packages/react/index.js
  packages/react/index.modern.fb.js
  packages/react/index.stable.js
  packages/react/src/React.js
  packages/react/src/ReactHooks.js
  packages/react/unstable-shared-subset.experimental.js
Labels: CLA Signed, React Core Team

#22670 Remove @flow pragma comment from module registration start/stop templates
  packages/shared/registerInternalModuleStart.js
  packages/shared/registerInternalModuleStop.js
Labels: CLA Signed, React Core Team

#22672 Remove experimental useOpaqueIdentifier API
  packages/react-art/src/ReactARTHostConfig.js
  packages/react-debug-tools/src/ReactDebugHooks.js
  packages/react-debug-tools/src/__tests__/ReactHooksInspectionIntegration-test.js
  packages/react-devtools-shared/src/backend/ReactSymbols.js
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationHooks-test.js
  packages/react-dom/src/client/DOMPropertyOperations.js
  packages/react-dom/src/client/ReactDOMComponent.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom/src/server/ReactDOMServerLegacyFormatConfig.js
  packages/react-dom/src/server/ReactPartialRenderer.js
  packages/react-dom/src/server/ReactPartialRendererHooks.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeHostConfig.js
  packages/react-native-renderer/src/server/ReactNativeServerFormatConfig.js
  packages/react-noop-renderer/src/ReactNoopServer.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/ReactInternalTypes.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js
  packages/react-reconciler/src/forks/ReactFiberHostConfig.custom.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-server/src/forks/ReactServerFormatConfig.custom.js
  packages/react-suspense-test-utils/src/ReactSuspenseTestUtils.js
  packages/react-test-renderer/src/ReactTestHostConfig.js
  packages/react/index.classic.fb.js
  packages/react/index.experimental.js
  packages/react/index.js
  packages/react/index.modern.fb.js
  packages/react/index.stable.js
  packages/react/src/React.js
  packages/react/src/ReactHooks.js
  packages/react/unstable-shared-subset.experimental.js
  packages/shared/CheckStringCoercion.js
  packages/shared/ReactSymbols.js
  scripts/error-codes/codes.json
Labels: CLA Signed, React Core Team

#22674 Upgrade useId to alpha channel
  packages/react-debug-tools/src/__tests__/ReactHooksInspectionIntegration-test.js
  packages/react-dom/src/__tests__/ReactDOMUseId-test.js
  packages/react/index.classic.fb.js
  packages/react/index.experimental.js
  packages/react/index.js
  packages/react/index.modern.fb.js
  packages/react/index.stable.js
  packages/react/src/React.js
  packages/react/unstable-shared-subset.experimental.js
Labels: CLA Signed, React Core Team

#22669 Fix DevTools advanced tooltip display conditional check
  packages/react-devtools-shared/src/devtools/views/Profiler/SnapshotCommitList.js
Labels: CLA Signed, Component: Developer Tools, React Core Team

#22681 Fix useId in strict mode
  packages/react-dom/src/__tests__/ReactDOMUseId-test.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberTreeContext.new.js
  packages/react-reconciler/src/ReactFiberTreeContext.old.js
  packages/react-server/src/ReactFizzHooks.js
Labels: CLA Signed, React Core Team

#22690 Rename (some) "scheduling profiler" references to "timeline"
  packages/react-devtools-extensions/src/main.js
  packages/react-devtools-scheduling-profiler/README.md
  packages/react-devtools-scheduling-profiler/src/content-views/constants.js
  packages/react-devtools-scheduling-profiler/src/import-worker/preprocessData.js
  packages/react-devtools-shared/src/backend/types.js
  packages/react-devtools-shared/src/constants.js
  packages/react-devtools-shared/src/devtools/views/ErrorBoundary/cache.js
  packages/react-devtools-shared/src/devtools/views/Icon.js
  packages/react-devtools-shared/src/devtools/views/Profiler/ClearProfilingDataButton.js
  packages/react-devtools-shared/src/devtools/views/Profiler/Profiler.js
  packages/react-devtools-shared/src/devtools/views/Profiler/ProfilerContext.js
  packages/react-devtools-shared/src/devtools/views/Profiler/ProfilingImportExportButtons.js
  packages/react-devtools-shared/src/dynamicImportCache.js
  packages/react-devtools-shared/src/hookNamesCache.js
  packages/react-devtools-shared/src/inspectedElementCache.js
  packages/react-reconciler/src/ReactFiberLane.new.js
  packages/react-reconciler/src/ReactFiberLane.old.js
  packages/react-reconciler/src/SchedulingProfiler.js
  packages/shared/ReactFeatureFlags.js
  scripts/rollup/wrappers.js
Labels: CLA Signed, React Core Team

#22688 Fix module-boundary wrappers
  scripts/rollup/wrappers.js
  scripts/rollup/wrappers/registerInternalModuleBegin.js
  scripts/rollup/wrappers/registerInternalModuleEnd.js
Labels: CLA Signed, React Core Team

#22696 Cleaned up remaining "scheduling profiler" references in DevTools
  packages/react-devtools-extensions/src/main.js
  packages/react-devtools-inline/src/frontend.js
  packages/react-devtools-shared/src/devtools/store.js
  packages/react-devtools-shared/src/devtools/views/DevTools.js
  packages/react-devtools-shared/src/devtools/views/Profiler/ClearProfilingDataButton.js
  packages/react-devtools-shared/src/devtools/views/Profiler/Profiler.js
  packages/react-devtools-shared/src/devtools/views/Profiler/ProfilingImportExportButtons.js
  packages/react-devtools-timeline/src/Timeline.css
  packages/react-devtools-timeline/src/Timeline.js
  packages/react-devtools-timeline/src/TimelineContext.js
Labels: CLA Signed, React Core Team

#22701 Fix small typos
  packages/react-devtools-shared/src/__tests__/console-test.js
  packages/react-devtools-shared/src/backend/views/utils.js
  scripts/release/prepare-release-from-npm-commands/update-stable-version-numbers.js
Labels: CLA Signed

#22599 devtools: Display root type for root updates in "what caused this update?"
  packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-devtools-shared/src/devtools/views/Profiler/Updaters.js
Labels: CLA Signed, Component: Developer Tools

#22710 Delete unused Circle CI scripts.
  scripts/circleci/add_build_info_json.sh
  scripts/circleci/bench.sh
  scripts/circleci/check_minified_errors.sh
  scripts/circleci/pack_and_store_artifact.sh
  scripts/circleci/set_up_github_keys.sh
  scripts/circleci/test_coverage.sh
  scripts/circleci/update_package_versions.sh
  scripts/release/ci-add-build-info-json.js
  scripts/release/ci-update-package-versions.js
Labels: CLA Signed

#22706 Timeline: Improved snapshot view
  packages/react-devtools-timeline/src/CanvasPage.js
  packages/react-devtools-timeline/src/EventTooltip.js
  packages/react-devtools-timeline/src/constants.js
  packages/react-devtools-timeline/src/content-views/SnapshotsView.js
  packages/react-devtools-timeline/src/content-views/constants.js
  packages/react-devtools-timeline/src/import-worker/__tests__/preprocessData-test.internal.js
  packages/react-devtools-timeline/src/import-worker/preprocessData.js
  packages/react-devtools-timeline/src/types.js
  packages/react-devtools-timeline/src/view-base/View.js
Labels: CLA Signed, React Core Team

#22716 fix(devtools): expose css vars to reach-ui portal components
  packages/react-devtools-shared/src/devtools/views/Button.js
  packages/react-devtools-shared/src/devtools/views/Components/OwnersStack.js
  packages/react-devtools-shared/src/devtools/views/Components/reach-ui/Tooltip.css
  packages/react-devtools-shared/src/devtools/views/Components/reach-ui/menu-button.js
  packages/react-devtools-shared/src/devtools/views/Components/reach-ui/tooltip.js
  packages/react-devtools-shared/src/devtools/views/Settings/SettingsContext.js
  packages/react-devtools-shared/src/devtools/views/TabBar.js
  packages/react-devtools-shared/src/devtools/views/ThemeProvider.js
  packages/react-devtools-shared/src/devtools/views/Toggle.js
  packages/react-devtools-shared/src/devtools/views/root.css
  packages/react-devtools-shared/src/devtools/views/useThemeStyles.js
Labels: CLA Signed

#22717 fix(devtools): accept json file in import fileinput
  packages/react-devtools-shared/src/devtools/views/Profiler/ProfilingImportExportButtons.js
  packages/react-devtools-timeline/src/ImportButton.js
Labels: CLA Signed

#22629 Throw on hydration mismatch and force client rendering if boundary hasn't suspended within concurrent root
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-reconciler/src/ReactFiberHydrationContext.new.js
  packages/react-reconciler/src/ReactFiberHydrationContext.old.js
  packages/react-reconciler/src/ReactFiberThrow.new.js
  packages/react-reconciler/src/ReactFiberThrow.old.js
  scripts/error-codes/codes.json
Labels: CLA Signed, React Core Team

#22621 [React Refresh] support typescript namespace syntax
  package.json
  packages/react-refresh/src/ReactFreshBabelPlugin.js
  packages/react-refresh/src/__tests__/ReactFreshBabelPlugin-test.js
  packages/react-refresh/src/__tests__/ReactFreshIntegration-test.js
  packages/react-refresh/src/__tests__/__snapshots__/ReactFreshBabelPlugin-test.js.snap
  yarn.lock
Labels: CLA Signed

#22730 Add Scheduling Profiler GK link to Timeline UI for FB build
  packages/react-devtools-timeline/src/Timeline.js
Labels: CLA Signed, React Core Team

#22745 Filter empty commits (all Fibers bailed out) from Profiler
  packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap
  packages/react-devtools-shared/src/__tests__/profilerStore-test.js
  packages/react-devtools-shared/src/__tests__/profilingCache-test.js
  packages/react-devtools-shared/src/backend/renderer.js
Labels: CLA Signed, React Core Team

#22746 DevTools should properly report re-renders due to (use)context changes
  packages/react-devtools-shared/src/__tests__/profilerChangeDescriptions-test.js
  packages/react-devtools-shared/src/backend/renderer.js
Labels: CLA Signed, Component: Developer Tools, React Core Team

#22748 Add runtime type checks around module boundary code
  packages/react-reconciler/src/SchedulingProfiler.js
Labels: CLA Signed, React Core Team

#22750 Re-enable useMutableSource in internal RN
  packages/shared/forks/ReactFeatureFlags.native-fb.js
Labels: CLA Signed, React Core Team

#22753 devtools: dont restore profiling data if we're profling
  packages/react-devtools-extensions/src/main.js
Labels: CLA Signed

#22715 Fix some typos
  packages/react-dom/src/__tests__/CSSPropertyOperations-test.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberTreeContext.new.js
  packages/react-reconciler/src/ReactFiberTreeContext.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-server/src/ReactFizzTreeContext.js
  scripts/release/README.md
Labels: CLA Signed

#22657 chore: fix comment typo
  packages/react-reconciler/src/__tests__/ReactCache-test.js
Labels: CLA Signed

#22764 fix : grammatical typo for test description
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js
Labels: CLA Signed

#22763 Fixed typos
  scripts/jest/matchers/toThrow.js
  scripts/release/README.md
Labels: CLA Signed

#22765 Move SuspenseList to experimental channel
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-dom/src/__tests__/ReactDOMServerSuspense-test.internal.js
  packages/react-dom/src/__tests__/ReactWrongReturnPointer-test.js
  packages/react-is/src/__tests__/ReactIs-test.js
  packages/react-reconciler/src/__tests__/ReactContextPropagation-test.js
  packages/react-reconciler/src/__tests__/ReactHooksWithNoopRenderer-test.js
  packages/react-reconciler/src/__tests__/ReactSuspenseList-test.js
  packages/react-server-dom-relay/src/__tests__/ReactFlightDOMRelay-test.internal.js
  packages/react/index.stable.js
  scripts/jest/TestFlags.js
Labels: CLA Signed, React Core Team

#22766 Bump 18 from alpha to beta
  .circleci/config.yml
  ReactVersions.js
Labels: CLA Signed, React Core Team

#22768 Allow publishing with `beta` tag
  scripts/release/publish-commands/parse-params.js
Labels: CLA Signed, React Core Team

#22754 Proof of Concept for E2E tests using playwright
  packages/react-devtools-inline/__tests__/__e2e__/inspecting-props.test.js
  packages/react-devtools-inline/package.json
  packages/react-devtools-inline/playwright.config.js
  packages/react-devtools-shell/webpack.config.js
Labels: CLA Signed

#22455 Move unstable_scheduleHydration to ReactDOMHydrationRoot
  packages/react-dom/index.classic.fb.js
  packages/react-dom/index.experimental.js
  packages/react-dom/index.js
  packages/react-dom/index.modern.fb.js
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-dom/src/__tests__/ReactDOMServerSelectiveHydration-test.internal.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMRoot.js
Labels: CLA Signed, React Core Team

#22779 Remove "packages/shared/invariant.js"
  packages/shared/invariant.js
Labels: CLA Signed

#22778 Remove unused "react-internal/invariant-args" ESLint rule.
  .eslintrc.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/InitializeNativeFabricUIManager.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativeViewConfigRegistry.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/UIManager.js
  scripts/eslint-rules/__tests__/invariant-args-test.internal.js
  scripts/eslint-rules/index.js
  scripts/eslint-rules/invariant-args.js
  scripts/rollup/shims/react-native/ReactNativeViewConfigRegistry.js
Labels: CLA Signed

#22777 Use globalThis if possible to access fetch in react-fetch browser build
  packages/react-fetch/src/ReactFetchBrowser.js
  scripts/rollup/validate/eslintrc.cjs.js
Labels: CLA Signed

#22760 Add test selectors to experimental build
  package.json
  packages/react-devtools-inline/webpack.config.js
  packages/react-devtools-shell/webpack.config.js
  packages/react-dom/npm/unstable_testing.js
  packages/react-dom/package.json
  packages/react-dom/src/__tests__/ReactDOMTestSelectors-test.internal.js
  packages/react-dom/testing.experimental.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  scripts/rollup/bundles.js
Labels: CLA Signed, React Core Team

#22780 fix(typo): Esacpe -> Escape
  packages/react-interactions/events/src/dom/create-event-handle/Focus.js
Labels: CLA Signed

#22787 Flag for client render fallback behavior on hydration mismatch
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-reconciler/src/ReactFiberHydrationContext.new.js
  packages/react-reconciler/src/ReactFiberHydrationContext.old.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www-dynamic.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#22783 Solve DEP0148
  packages/react/package.json
Labels: CLA Signed

#22756 Migrate from CLIEngine to the new ESLint class.
  scripts/eslint/index.js
  scripts/tasks/eslint.js
  scripts/tasks/linc.js
Labels: CLA Signed

#22740 Track late-mounted roots in Fast Refresh
  packages/react-refresh/src/ReactFreshRuntime.js
Labels: CLA Signed

#22792 Revert "Fix Node package.json ./ exports deprecation warning (#22783)"
  packages/react/package.json
Labels: CLA Signed

#22790 Ensure devtools e2e test use a compatible react-is version
  package.json
  yarn.lock
Labels: CLA Signed

#22813 Ensure react-is version used for resolution for playwright is installed
  package.json
  yarn.lock
Labels: CLA Signed, Component: Developer Tools

#22767 Update deprecated features in ESLint configuration files.
  .eslintrc.js
  scripts/rollup/validate/eslintrc.cjs.js
  scripts/rollup/validate/eslintrc.cjs2015.js
  scripts/rollup/validate/eslintrc.esm.js
  scripts/rollup/validate/eslintrc.fb.js
  scripts/rollup/validate/eslintrc.rn.js
  scripts/rollup/validate/eslintrc.umd.js
Labels: CLA Signed

#22807 Treat empty string as null
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationElements-test.js
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-dom/src/__tests__/ReactMultiChildText-test.js
  packages/react-reconciler/src/ReactChildFiber.new.js
  packages/react-reconciler/src/ReactChildFiber.old.js
  packages/react-reconciler/src/__tests__/ReactIncrementalUpdates-test.js
Labels: CLA Signed, React Core Team

#22695 fix: document can be `null`, not just `undefined`
  packages/shared/invokeGuardedCallbackImpl.js
Labels: CLA Signed

#22522 Update attribute-behavior fixture
  fixtures/attribute-behavior/.gitignore
  fixtures/attribute-behavior/AttributeTableSnapshot.md
  fixtures/attribute-behavior/README.md
  fixtures/attribute-behavior/package.json
  fixtures/attribute-behavior/src/App.js
Labels: CLA Signed

#22550 Add `imageSizes` and `imageSrcSet` to know props
  fixtures/attribute-behavior/AttributeTableSnapshot.md
  fixtures/attribute-behavior/src/attributes.js
  packages/react-dom/src/shared/possibleStandardNames.js
Labels: CLA Signed

#22739 update ReactFlightWebpackPlugin to be compatiable with webpack v5
  packages/react-server-dom-webpack/package.json
  packages/react-server-dom-webpack/src/ReactFlightWebpackPlugin.js
Labels: CLA Signed

#22825 DevTools: Log version in internal logger
  packages/react-devtools-shared/src/registerDevToolsEventLogger.js
Labels: CLA Signed, Component: Developer Tools
