Repository facebook/react, pull requests merged in 2022-03, with the labels that each got.

#23387 Remove hacky stream.locked check, declare as byte stream instead
  packages/react-dom/src/server/ReactDOMFizzServerBrowser.js
  packages/react-server-dom-webpack/src/ReactFlightDOMServerBrowser.js
Labels: CLA Signed

#23393 Refactor Cache Code
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberCacheComponent.new.js
  packages/react-reconciler/src/ReactFiberCacheComponent.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberTransition.new.js
  packages/react-reconciler/src/ReactFiberTransition.old.js
  packages/react-reconciler/src/ReactFiberTransitionPool.old.js
  packages/react-reconciler/src/ReactFiberUnwindWork.new.js
  packages/react-reconciler/src/ReactFiberUnwindWork.old.js
Labels: CLA Signed, React Core Team

#23395 reassign src from props not the dom element src property
  packages/react-dom/src/__tests__/ReactDOMImageLoad-test.internal.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
Labels: CLA Signed

#23399 Show DevTools backend and frontend versions in UI
  packages/react-devtools-shared/src/backend/agent.js
  packages/react-devtools-shared/src/bridge.js
  packages/react-devtools-shared/src/devtools/store.js
  packages/react-devtools-shared/src/devtools/views/Settings/GeneralSettings.js
  packages/react-devtools-shared/src/devtools/views/Settings/SettingsShared.css
  packages/react-devtools-shell/src/app/index.js
  packages/react-devtools/CHANGELOG.md
Labels: CLA Signed, Component: Developer Tools, React Core Team

#23400 React DevTools 4.23.0 -> 4.24.0
  packages/react-devtools-core/package.json
  packages/react-devtools-extensions/chrome/manifest.json
  packages/react-devtools-extensions/edge/manifest.json
  packages/react-devtools-extensions/firefox/manifest.json
  packages/react-devtools-inline/package.json
  packages/react-devtools-timeline/package.json
  packages/react-devtools/CHANGELOG.md
  packages/react-devtools/package.json
  scripts/devtools/prepare-release.js
Labels: CLA Signed, Component: Developer Tools, React Core Team

#23195 ReactART:-Added unit Tests in the ReactART, increasing the code coverage
  packages/react-art/src/__tests__/ReactART-test.js
  packages/react-art/src/__tests__/__snapshots__/ReactART-test.js.snap
Labels: CLA Signed

#23386 Fabric HostComponent as EventEmitter: support add/removeEventListener (unstable only)
  packages/react-native-renderer/src/ReactFabricEventEmitter.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeBridgeEventPlugin.js
  packages/react-native-renderer/src/ReactNativeEventEmitter.js
  packages/react-native-renderer/src/ReactNativeGetListener.js
  packages/react-native-renderer/src/ReactNativeGetListeners.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/CustomEvent.js
  packages/react-native-renderer/src/__mocks__/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js
  packages/react-native-renderer/src/legacy-events/PropagationPhases.js
  scripts/flow/react-native-host-hooks.js
Labels: CLA Signed

#24024 [Fizz] Export debug function for FB
  packages/react-server-dom-relay/src/ReactDOMServerFB.js
Labels: CLA Signed, React Core Team

#24025 Move onCompleteAll to .allReady Promise
  packages/react-dom/src/__tests__/ReactDOMFizzServerBrowser-test.js
  packages/react-dom/src/server/ReactDOMFizzServerBrowser.js
  packages/react-dom/src/server/ReactDOMFizzServerNode.js
  packages/react-dom/src/server/ReactDOMLegacyServerBrowser.js
  packages/react-dom/src/server/ReactDOMLegacyServerNode.js
  packages/react-server/src/ReactFizzServer.js
Labels: CLA Signed

#24030 Rename Node SSR Callbacks to onShellReady/onAllReady and Other Fixes
  fixtures/ssr/server/render.js
  fixtures/ssr2/server/render.js
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMFizzServerBrowser-test.js
  packages/react-dom/src/__tests__/ReactDOMFizzServerNode-test.js
  packages/react-dom/src/__tests__/utils/ReactDOMServerIntegrationTestUtils.js
  packages/react-dom/src/server/ReactDOMFizzServerBrowser.js
  packages/react-dom/src/server/ReactDOMFizzServerNode.js
  packages/react-dom/src/server/ReactDOMLegacyServerBrowser.js
  packages/react-dom/src/server/ReactDOMLegacyServerNode.js
  packages/react-noop-renderer/src/ReactNoopServer.js
  packages/react-server/src/ReactFizzServer.js
Labels: CLA Signed

#24034 [Fizz] write chunks to a buffer with no re-use
  packages/react-dom/src/__tests__/ReactDOMFizzServerBrowser-test.js
  packages/react-server/src/ReactServerStreamConfigBrowser.js
Labels: CLA Signed

#24037 Add more feature flag checks
  packages/react-reconciler/src/ReactFiber.new.js
  packages/react-reconciler/src/ReactFiber.old.js
  packages/react-reconciler/src/__tests__/DebugTracing-test.internal.js
  packages/shared/getComponentNameFromType.js
  packages/shared/isValidElementType.js
Labels: CLA Signed

#24038 Gate unstable_expectedLoadTime on enableCPUSuspense
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/__tests__/DebugTracing-test.internal.js
  packages/react-reconciler/src/__tests__/ReactCPUSuspense-test.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed

#24043 Fizz: Prevent `UnhandledPromiseRejectionWarning` if `renderToReadableStream` throws
  packages/react-dom/src/server/ReactDOMFizzServerBrowser.js
Labels: CLA Signed

#24054 [Fizz] Don't flush empty segments
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-server/src/ReactFizzServer.js
Labels: CLA Signed

#24055 [Flight] Update test to reset modules instead of using private state
  packages/react-client/src/__tests__/ReactFlight-test.js
Labels: CLA Signed

#24047 Gate legacy hidden
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-dom/src/__tests__/ReactUpdates-test.js
  packages/react-reconciler/src/ReactFiber.new.js
  packages/react-reconciler/src/ReactFiber.old.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/__tests__/ReactContextPropagation-test.js
  packages/react-reconciler/src/__tests__/ReactIncremental-test.js
  packages/react-reconciler/src/__tests__/ReactIncrementalErrorHandling-test.internal.js
  packages/react-reconciler/src/__tests__/ReactIncrementalSideEffects-test.js
  packages/react-reconciler/src/__tests__/ReactNewContext-test.js
  packages/react-reconciler/src/__tests__/ReactOffscreen-test.js
  packages/react-reconciler/src/__tests__/ReactSchedulerIntegration-test.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.js
  packages/react-reconciler/src/getComponentNameFromFiber.js
  packages/react-refresh/src/__tests__/ReactFresh-test.js
  packages/react/index.experimental.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  packages/shared/isValidElementType.js
Labels: CLA Signed

#24031 Fixed edge case bug in Profiler
  packages/react-devtools-shared/src/__tests__/__snapshots__/profilingCache-test.js.snap
  packages/react-devtools-shared/src/__tests__/profilingCache-test.js
  packages/react-devtools-shared/src/backend/renderer.js
Labels: CLA Signed, React Core Team

#24065 Better handle undefined Error stacks in DevTools error boundary
  packages/react-devtools-shared/src/devtools/views/ErrorBoundary/ErrorBoundary.js
Labels: CLA Signed, React Core Team

#24066 React DevTools 4.23.0 -> 4.24.0
  packages/react-devtools/CHANGELOG.md
Labels: CLA Signed, React Core Team

#24068 [Flight] add support for Lazy components in Flight server
  packages/react-client/src/__tests__/ReactFlight-test.js
  packages/react-server/src/ReactFlightServer.js
Labels: CLA Signed

#24080 Allow updating dehydrated root at lower priority without forcing client render
  packages/react-art/src/ReactART.js
  packages/react-dom/src/__tests__/ReactDOMRoot-test.js
  packages/react-dom/src/client/ReactDOMLegacy.js
  packages/react-dom/src/client/ReactDOMRoot.js
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiberReconciler.new.js
  packages/react-reconciler/src/ReactFiberReconciler.old.js
  packages/react-reconciler/src/__tests__/ReactFiberHostContext-test.internal.js
  packages/react-test-renderer/src/ReactTestRenderer.js
Labels: CLA Signed, React Core Team

#24081 Revert accidentally merged PR #24080
  packages/react-art/src/ReactART.js
  packages/react-dom/src/__tests__/ReactDOMFizzShellHydration-test.js
  packages/react-dom/src/__tests__/ReactDOMRoot-test.js
  packages/react-dom/src/client/ReactDOMLegacy.js
  packages/react-dom/src/client/ReactDOMRoot.js
  packages/react-dom/src/events/ReactDOMEventListener.js
  packages/react-dom/src/events/ReactDOMEventReplaying.js
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberReconciler.new.js
  packages/react-reconciler/src/ReactFiberReconciler.old.js
  packages/react-reconciler/src/ReactFiberRoot.new.js
  packages/react-reconciler/src/ReactFiberRoot.old.js
  packages/react-reconciler/src/ReactFiberShellHydration.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/ReactInternalTypes.js
  packages/react-reconciler/src/__tests__/ReactFiberHostContext-test.internal.js
  packages/react-test-renderer/src/ReactTestRenderer.js
Labels: CLA Signed, React Core Team

#24077 Match select value against primitives to string but not undefined
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationSelect-test.js
  packages/react-dom/src/server/ReactDOMServerFormatConfig.js
Labels: CLA Signed

#24084 Fix use of hydrateRoot in DevTools test
  packages/react-devtools-shared/src/__tests__/inspectedElement-test.js
Labels: CLA Signed, React Core Team

#24086 Don't hide console error|warn in inspectedElement-test
  packages/react-devtools-shared/src/__tests__/inspectedElement-test.js
Labels: CLA Signed

#23366 Add skipBubbling property to dispatch config
  packages/react-native-renderer/src/ReactNativeBridgeEventPlugin.js
  packages/react-native-renderer/src/ReactNativeTypes.js
  packages/react-native-renderer/src/__tests__/ReactFabric-test.internal.js
  packages/react-native-renderer/src/legacy-events/ReactSyntheticEventType.js
  scripts/rollup/shims/react-native/ReactNativeViewConfigRegistry.js
Labels: CLA Signed

#24093 Disable unsupported protocol version dialog and add workaround
  packages/react-devtools-core/src/standalone.js
  packages/react-devtools-shared/src/bridge.js
  packages/react-devtools-shared/src/devtools/store.js
  packages/react-devtools-shared/src/devtools/views/UnsupportedBridgeProtocolDialog.js
  packages/react-devtools-shared/src/devtools/views/hooks.js
Labels: CLA Signed, React Core Team

#24100 React DevTools 4.24.0 -> 4.24.1
  packages/react-devtools-core/package.json
  packages/react-devtools-extensions/chrome/manifest.json
  packages/react-devtools-extensions/edge/manifest.json
  packages/react-devtools-extensions/firefox/manifest.json
  packages/react-devtools-inline/package.json
  packages/react-devtools-timeline/package.json
  packages/react-devtools/CHANGELOG.md
  packages/react-devtools/package.json
Labels: CLA Signed, React Core Team

#24026 Add Offscreen stateNode
  packages/react-reconciler/src/ReactFiber.new.js
  packages/react-reconciler/src/ReactFiber.old.js
  packages/react-reconciler/src/ReactFiberOffscreenComponent.js
Labels: CLA Signed, React Core Team

#24106 Add authorization header to artifacts request
  .circleci/config.yml
  scripts/release/shared-commands/download-build-artifacts.js
Labels: CLA Signed, React Core Team

#24107 Flag for text hydration mismatch
  packages/react-dom/src/__tests__/ReactDOMServerPartialHydration-test.internal.js
  packages/react-dom/src/client/ReactDOMComponent.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www-dynamic.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#24105 Update DevTools READMEs
  packages/react-devtools-core/README.md
  packages/react-devtools-inline/README.md
  packages/react-devtools-shared/README.md
  packages/react-devtools/OVERVIEW.md
  packages/react-devtools/README.md
Labels: CLA Signed, React Core Team

#24109 Fix dispatch config type for skipBubbling
  packages/react-native-renderer/src/ReactNativeTypes.js
Labels: CLA Signed

#24110 Fix createRoot/hydrateRoot container signature
  packages/react-dom/client.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMComponent.js
  packages/react-dom/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/client/ReactDOMRoot.js
Labels: CLA Signed

#24116 [DevTools] fix inspecting an element in a nested renderer bug
  packages/react-devtools-shared/src/__tests__/inspectedElement-test.js
  packages/react-devtools-shared/src/backend/renderer.js
Labels: CLA Signed, React Core Team

#24126 Avoid conditions where control flow is sufficient
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
Labels: CLA Signed

#24082 Allow updating dehydrated root at lower priority without forcing client render
  packages/react-art/src/ReactART.js
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-dom/src/__tests__/ReactDOMFizzShellHydration-test.js
  packages/react-dom/src/__tests__/ReactDOMRoot-test.js
  packages/react-dom/src/client/ReactDOMLegacy.js
  packages/react-dom/src/client/ReactDOMRoot.js
  packages/react-dom/src/events/ReactDOMEventListener.js
  packages/react-dom/src/events/ReactDOMEventReplaying.js
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberReconciler.new.js
  packages/react-reconciler/src/ReactFiberReconciler.old.js
  packages/react-reconciler/src/ReactFiberRoot.new.js
  packages/react-reconciler/src/ReactFiberRoot.old.js
  packages/react-reconciler/src/ReactFiberShellHydration.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/ReactInternalTypes.js
  packages/react-reconciler/src/__tests__/ReactFiberHostContext-test.internal.js
  packages/react-test-renderer/src/ReactTestRenderer.js
Labels: CLA Signed, React Core Team

#24131 enableCacheElement flag
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  packages/shared/isValidElementType.js
Labels: CLA Signed

#24141 Bump versions to rc.3
  ReactVersions.js
Labels: CLA Signed, React Core Team

#24088 Fix test-build-devtools if build was generated by build-for-devtools
  package.json
  packages/shared/ReactVersion.js
Labels: CLA Signed

#24147 Store throws a specific Error type (UnsupportedBridgeOperationError)
  packages/react-devtools-shared/src/UnsupportedBridgeOperationError.js
  packages/react-devtools-shared/src/devtools/store.js
  packages/react-devtools-shared/src/devtools/views/ErrorBoundary/ErrorBoundary.js
  packages/react-devtools-shared/src/devtools/views/ErrorBoundary/UnsupportedBridgeOperationView.js
  packages/react-devtools-shared/src/devtools/views/ErrorBoundary/shared.css
Labels: CLA Signed, React Core Team

#24150 React DevTools 4.24.1 -> 4.24.2
  packages/react-devtools-core/package.json
  packages/react-devtools-extensions/chrome/manifest.json
  packages/react-devtools-extensions/edge/manifest.json
  packages/react-devtools-extensions/firefox/manifest.json
  packages/react-devtools-inline/package.json
  packages/react-devtools-timeline/package.json
  packages/react-devtools/CHANGELOG.md
  packages/react-devtools/package.json
Labels: CLA Signed, React Core Team

#24154 Release script prompts to stop running DEV scripts
  scripts/devtools/build-and-test.js
Labels: CLA Signed, React Core Team

#24163 DevTools imports
  packages/react-devtools-core/src/standalone.js
  packages/react-devtools-extensions/src/main.js
  packages/react-devtools-shell/src/app/Iframe/index.js
  packages/react-devtools-shell/src/app/devtools.js
  packages/react-devtools-shell/src/app/index.js
  packages/react-devtools-shell/src/e2e/app.js
  packages/react-devtools-shell/src/e2e/devtools.js
  packages/react-devtools-shell/src/multi/devtools.js
Labels: CLA Signed, React Core Team

#24164 Attach DevTools Tree keyboard events to the Tree container (not the document)
  packages/react-devtools-shared/src/devtools/views/Components/Tree.js
Labels: CLA Signed, React Core Team

#24166 [fizz] Fix validateIterable call
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-server/src/ReactFizzServer.js
Labels: CLA Signed, React Core Team

#24186 DevTools bugfix: Ignore duplicate welcome "message" events
  packages/react-devtools-extensions/src/backend.js
  packages/react-devtools-extensions/src/contentScript.js
Labels: CLA Signed, React Core Team

#24188 Fix usage of console.error to prevent transform
  packages/react-dom/src/client/ReactDOMRoot.js
Labels: CLA Signed

#24190 Remove rc suffix from versions
  ReactVersions.js
Labels: CLA Signed, React Core Team

#24195 Add React 18 changelog
  CHANGELOG.md
Labels: CLA Signed

#24198 React DevTools 4.24.2 -> 4.24.3
  packages/react-devtools-core/package.json
  packages/react-devtools-extensions/chrome/manifest.json
  packages/react-devtools-extensions/edge/manifest.json
  packages/react-devtools-extensions/firefox/manifest.json
  packages/react-devtools-inline/package.json
  packages/react-devtools-timeline/package.json
  packages/react-devtools/CHANGELOG.md
  packages/react-devtools/package.json
Labels: CLA Signed

#24206 Update CHANGELOG.md
  CHANGELOG.md
Labels: CLA Signed

#24193 fix local build script for react dev tools
  package.json
Labels: CLA Signed

#24200 DevTools release script: Show changelog before minor/patch prompt
  scripts/devtools/prepare-release.js
Labels: CLA Signed, React Core Team

#24209 Remove unstable_createMutableSource from experimental build
  packages/react/index.experimental.js
Labels: CLA Signed

#24218 Update @next version
  ReactVersions.js
Labels: CLA Signed, React Core Team

#24220 Remove React 18 issue template
  .github/ISSUE_TEMPLATE/react_18.md
Labels: CLA Signed, React Core Team

#24234 Add 4.4.0 release to eslint rules CHANGELOG
  packages/eslint-plugin-react-hooks/CHANGELOG.md
Labels: CLA Signed, React Core Team

#24229 Test suite for hydration diff warnings
  packages/react-dom/src/__tests__/ReactDOMHydrationDiff-test.js
Labels: CLA Signed, React Core Team

#24237 Fix for SSR2 fixture not working locally
  fixtures/ssr2/README.md
  fixtures/ssr2/scripts/build.js
  fixtures/ssr2/server/render.js
Labels: CLA Signed
