Repository facebook/react, pull requests merged in 2022-10, with the labels that each got.

#25378 Fix failing tests in latest 16.x and 18.x Node versions
  packages/react-dom/src/__tests__/ReactTestUtilsAct-test.js
Labels: CLA Signed

#25362 Flow: enable well_formed_exports for reconciler
  packages/react-reconciler/src/ReactChildFiber.new.js
  packages/react-reconciler/src/ReactChildFiber.old.js
  packages/react-reconciler/src/ReactFiberClassComponent.new.js
  packages/react-reconciler/src/ReactFiberClassComponent.old.js
  packages/react-reconciler/src/ReactFiberContext.new.js
  packages/react-reconciler/src/ReactFiberContext.old.js
  packages/react-reconciler/src/ReactFiberHotReloading.js
  packages/react-reconciler/src/ReactFiberReconciler.js
  packages/react-reconciler/src/ReactFiberUnwindWork.new.js
  packages/react-reconciler/src/ReactFiberUnwindWork.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  scripts/flow/config/flowconfig
Labels: CLA Signed

#24611 Update Wedge.js
  packages/react-art/npm/Wedge.js
Labels: CLA Signed

#25374 CI: update CircleCI docker image
  .circleci/config.yml
Labels: CLA Signed, React Core Team

#25361 Flow: enable well_formed_exports for smaller packages
  packages/react-devtools-core/src/standalone.js
  packages/react-is/src/ReactIs.js
  packages/react-refresh/src/ReactFreshRuntime.js
  packages/react-server/src/ReactFlightHooks.js
  packages/use-sync-external-store/src/useSyncExternalStoreShim.js
  scripts/flow/config/flowconfig
Labels: CLA Signed

#25363 Flow: enable well_formed_exports for react-native-renderer
  packages/react-native-renderer/src/ReactFabric.js
  packages/react-native-renderer/src/ReactNativeBridgeEventPlugin.js
  packages/react-native-renderer/src/ReactNativeFiberInspector.js
  packages/react-native-renderer/src/ReactNativeRenderer.js
  packages/react-native-renderer/src/legacy-events/EventPluginRegistry.js
  packages/react-native-renderer/src/legacy-events/PluginModuleType.js
  scripts/flow/config/flowconfig
Labels: CLA Signed

#25348 Add NodeJS 18.x as devEngine
  package.json
Labels: CLA Signed

#25343 Flow: enable well_formed_exports for shared
  packages/react/src/ReactServerContextRegistry.js
  packages/shared/ReactErrorUtils.js
  packages/shared/ReactServerContextRegistry.js
  packages/shared/enqueueTask.js
  packages/shared/invokeGuardedCallbackImpl.js
  scripts/flow/config/flowconfig
Labels: CLA Signed

#25389 Flow: complete types first migration
  packages/react-devtools-shared/src/node_modules/react-window/src/FixedSizeGrid.js
  packages/react-devtools-shared/src/node_modules/react-window/src/FixedSizeList.js
  packages/react-devtools-shared/src/node_modules/react-window/src/VariableSizeGrid.js
  packages/react-devtools-shared/src/node_modules/react-window/src/VariableSizeList.js
  packages/react-dom-bindings/src/client/ReactDOMInput.js
  packages/react-dom-bindings/src/client/ReactDOMSelect.js
  packages/react-dom-bindings/src/client/ReactDOMTextarea.js
  packages/react-dom-bindings/src/client/setInnerHTML.js
  packages/react-dom-bindings/src/events/EventRegistry.js
  packages/react-dom-bindings/src/events/ReactDOMEventListener.js
  packages/react-dom-bindings/src/events/SyntheticEvent.js
  packages/react-dom-bindings/src/events/forks/EventListener-www.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/client/ReactDOMLegacy.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeHostConfig.js
  packages/react-native-renderer/src/legacy-events/accumulate.js
  packages/react-native-renderer/src/legacy-events/accumulateInto.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoHydration.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoMicrotasks.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoMutation.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoPersistence.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoResources.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoScopes.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoTestSelectors.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-test-renderer/src/ReactTestHostConfig.js
  packages/react-test-renderer/src/ReactTestRenderer.js
  packages/react/src/React.js
  packages/react/src/ReactDebugCurrentFrame.js
  packages/react/src/jsx/ReactJSX.js
  scripts/flow/config/flowconfig
Labels: CLA Signed, React Core Team

#25408 Flow upgrade to 0.143
  package.json
  packages/react-dom/src/server/ReactDOMFizzServerBrowser.js
  packages/react-dom/src/server/ReactDOMFizzStaticBrowser.js
  packages/react-reconciler/src/ReactStrictModeWarnings.new.js
  packages/react-reconciler/src/ReactStrictModeWarnings.old.js
  packages/react-refresh/src/ReactFreshRuntime.js
  packages/react-server-dom-webpack/src/ReactFlightDOMServerBrowser.js
  scripts/flow/config/flowconfig
  yarn.lock
Labels: CLA Signed, React Core Team

#25409 Flow upgrade to 0.145
  package.json
  packages/react-native-renderer/src/ReactNativeGetListeners.js
  scripts/flow/config/flowconfig
  scripts/flow/react-native-host-hooks.js
  yarn.lock
Labels: CLA Signed, React Core Team

#25410 Flow upgrade to 0.146
  package.json
  packages/react-devtools-core/src/editor.js
  packages/react-devtools-shared/src/backend/profilingHooks.js
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-devtools-shared/src/devtools/views/Components/OwnersListContext.js
  packages/react-devtools-shared/src/hooks/parseHookNames/parseSourceAndMetadata.js
  packages/react-devtools-shared/src/inspectedElementMutableSource.js
  packages/react-devtools/app.js
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/events/plugins/BeforeInputEventPlugin.js
  packages/react-dom-bindings/src/events/plugins/EnterLeaveEventPlugin.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-fs/src/ReactFilesystem.js
  packages/react-native-renderer/src/ReactNativeAttributePayload.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberHotReloading.new.js
  packages/react-reconciler/src/ReactFiberHotReloading.old.js
  packages/react-reconciler/src/ReactFiberSyncTaskQueue.new.js
  packages/react-reconciler/src/ReactFiberSyncTaskQueue.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-server-dom-webpack/src/ReactFlightWebpackPlugin.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFlightHooks.js
  packages/react-server/src/ReactServerStreamConfigNode.js
  packages/react-test-renderer/src/ReactTestRenderer.js
  packages/react/src/ReactStartTransition.js
  packages/scheduler/src/SchedulerProfiling.js
  packages/scheduler/src/forks/Scheduler.js
  packages/scheduler/src/forks/SchedulerMock.js
  scripts/flow/config/flowconfig
  yarn.lock
Labels: CLA Signed, React Core Team

#25411 Flow upgrade to 0.152
  package.json
  packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js
  packages/react-devtools-shared/src/devtools/views/utils.js
  packages/react-devtools-shared/src/utils.js
  scripts/flow/config/flowconfig
  yarn.lock
Labels: CLA Signed, React Core Team

#25412 Flow upgrade to 0.153
  package.json
  packages/jest-react/src/internalAct.js
  packages/react-cache/src/ReactCacheOld.js
  packages/react-devtools-shared/src/PerformanceLoggingUtils.js
  packages/react-devtools-shared/src/backend/profilingHooks.js
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-devtools-shared/src/backend/views/Highlighter/index.js
  packages/react-devtools-shared/src/backend/views/TraceUpdates/index.js
  packages/react-devtools-shared/src/backend/views/utils.js
  packages/react-devtools-shared/src/devtools/cache.js
  packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js
  packages/react-devtools-shared/src/devtools/views/Profiler/SidebarSelectedFiberInfo.js
  packages/react-devtools-shared/src/devtools/views/utils.js
  packages/react-devtools-shared/src/hook.js
  packages/react-devtools-shared/src/utils.js
  packages/react-devtools-timeline/src/import-worker/preprocessData.js
  packages/react-dom-bindings/src/client/ReactDOMComponent.js
  packages/react-dom-bindings/src/client/ReactDOMComponentTree.js
  packages/react-dom-bindings/src/client/ReactDOMHostConfig.js
  packages/react-dom-bindings/src/client/ReactDOMSelect.js
  packages/react-dom-bindings/src/client/inputValueTracking.js
  packages/react-dom-bindings/src/events/DOMPluginEventSystem.js
  packages/react-dom-bindings/src/server/ReactDOMLegacyServerStreamConfig.js
  packages/react-dom/src/client/ReactDOMLegacy.js
  packages/react-native-renderer/src/ReactFabricEventEmitter.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeFiberHostComponent.js
  packages/react-native-renderer/src/legacy-events/EventPluginRegistry.js
  packages/react-reconciler/src/ReactChildFiber.new.js
  packages/react-reconciler/src/ReactChildFiber.old.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberOffscreenComponent.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-server-dom-webpack/src/ReactFlightClientWebpackBundlerConfig.js
  packages/react-server-dom-webpack/src/ReactFlightWebpackNodeRegister.js
  packages/react-server-dom-webpack/src/ReactFlightWebpackPlugin.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFizzServer.js
  packages/react-server/src/ReactFlightHooks.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-server/src/ReactServerStreamConfigBrowser.js
  packages/react-server/src/ReactServerStreamConfigNode.js
  packages/react/src/ReactAct.js
  packages/scheduler/src/forks/Scheduler.js
  packages/shared/hasOwnProperty.js
  packages/shared/invokeGuardedCallbackImpl.js
  scripts/flow/config/flowconfig
  yarn.lock
Labels: CLA Signed, React Core Team

#25424 Flow: remove unused suppressions
  packages/react-cache/src/ReactCacheOld.js
  packages/react-client/src/ReactFlightClient.js
  packages/react-devtools-shared/src/backend/NativeStyleEditor/setupNativeStyleEditor.js
  packages/react-devtools-shared/src/backend/console.js
  packages/react-devtools-shared/src/backend/profilingHooks.js
  packages/react-devtools-shared/src/backend/renderer.js
  packages/react-devtools-shared/src/backend/views/Highlighter/index.js
  packages/react-devtools-shared/src/devtools/cache.js
  packages/react-devtools-shared/src/devtools/views/Components/InspectedElementHooksTree.js
  packages/react-devtools-shared/src/devtools/views/Components/Tree.js
  packages/react-devtools-shared/src/hook.js
  packages/react-devtools-shared/src/hooks/parseHookNames/parseSourceAndMetadata.js
  packages/react-devtools-shared/src/inspectedElementMutableSource.js
  packages/react-devtools-shell/src/app/DeeplyNestedComponents/index.js
  packages/react-devtools-shell/src/app/ElementTypes/index.js
  packages/react-devtools-timeline/src/view-base/utils/normalizeWheel.js
  packages/react-dom-bindings/src/client/ReactDOMComponent.js
  packages/react-dom-bindings/src/events/checkPassiveEvents.js
  packages/react-dom-bindings/src/events/plugins/BeforeInputEventPlugin.js
  packages/react-dom-bindings/src/events/plugins/ChangeEventPlugin.js
  packages/react-dom-bindings/src/events/plugins/EnterLeaveEventPlugin.js
  packages/react-dom-bindings/src/events/plugins/SelectEventPlugin.js
  packages/react-dom-bindings/src/events/plugins/SimpleEventPlugin.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/shared/DOMProperty.js
  packages/react-fs/src/ReactFilesystem.js
  packages/react-reconciler/src/ReactFiberAct.new.js
  packages/react-reconciler/src/ReactFiberAct.old.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberHotReloading.new.js
  packages/react-reconciler/src/ReactFiberHotReloading.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-refresh/src/ReactFreshRuntime.js
  packages/react-server-dom-webpack/src/ReactFlightWebpackNodeRegister.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFlightHooks.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-server/src/ReactFlightServerConfigStream.js
  packages/react/src/ReactStartTransition.js
  packages/scheduler/src/forks/SchedulerMock.js
Labels: CLA Signed, React Core Team

#25388 track resources in different roots separately
  packages/react-dom-bindings/src/client/ReactDOMComponentTree.js
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/client/ReactDOMHostConfig.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
  packages/react-reconciler/src/ReactFiberHostContext.js
  packages/react-reconciler/src/ReactFiberHostContext.new.js
  packages/react-reconciler/src/ReactFiberHostContext.old.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#25053 Include install command for devtools-extension build instructions
  packages/react-devtools-extensions/README.md
Labels: CLA Signed, Component: Developer Tools

#25432 [Float] Support script preloads
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/shared/ReactDOMResourceValidation.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
Labels: CLA Signed

#25433 [Float] add tests for resource emission when rendering no head or just a head
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
Labels: CLA Signed

#25442 Bugfix: LegacyHidden shouldn't defer effects
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/__tests__/ReactOffscreen-test.js
Labels: CLA Signed, React Core Team

#25441 [DevTools] Return `lastNonHostInstance` in `getInspectorDataForInstance`
  packages/react-native-renderer/src/ReactNativeFiberInspector.js
  packages/react-native-renderer/src/ReactNativeTypes.js
Labels: CLA Signed, React Core Team

#25436 Server render fork for react-dom
  packages/react-dom/npm/server-rendering-stub.js
  packages/react-dom/package.json
  packages/react-dom/server-rendering-stub.experimental.js
  packages/react-dom/server-rendering-stub.js
  packages/react-dom/src/__tests__/react-dom-server-rendering-stub-test.js
  packages/react-dom/src/server/ReactDOMServerRenderingStub.js
  scripts/error-codes/codes.json
  scripts/rollup/bundles.js
  scripts/rollup/forks.js
  scripts/shared/inlinedHostConfigs.js
Labels: CLA Signed

#25426 Implement HostSingleton
  packages/react-art/src/ReactARTHostConfig.js
  packages/react-dom-bindings/src/client/ReactDOMComponent.js
  packages/react-dom-bindings/src/client/ReactDOMComponentTree.js
  packages/react-dom-bindings/src/client/ReactDOMHostConfig.js
  packages/react-dom-bindings/src/events/DOMPluginEventSystem.js
  packages/react-dom-bindings/src/events/plugins/EnterLeaveEventPlugin.js
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
  packages/react-dom/src/__tests__/ReactDOMRoot-test.js
  packages/react-dom/src/__tests__/ReactDOMSingletonComponents-test.js
  packages/react-dom/src/__tests__/ReactRenderDocument-test.js
  packages/react-dom/src/__tests__/validateDOMNesting-test.js
  packages/react-dom/src/client/ReactDOMRoot.js
  packages/react-dom/src/events/__tests__/DOMPluginEventSystem-test.internal.js
  packages/react-dom/src/test-utils/ReactTestUtils.js
  packages/react-native-renderer/src/ReactFabricHostConfig.js
  packages/react-native-renderer/src/ReactNativeHostConfig.js
  packages/react-noop-renderer/src/createReactNoop.js
  packages/react-reconciler/src/ReactFiber.new.js
  packages/react-reconciler/src/ReactFiber.old.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberComponentStack.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoSingletons.js
  packages/react-reconciler/src/ReactFiberHotReloading.new.js
  packages/react-reconciler/src/ReactFiberHotReloading.old.js
  packages/react-reconciler/src/ReactFiberHydrationContext.new.js
  packages/react-reconciler/src/ReactFiberHydrationContext.old.js
  packages/react-reconciler/src/ReactFiberReconciler.new.js
  packages/react-reconciler/src/ReactFiberReconciler.old.js
  packages/react-reconciler/src/ReactFiberTreeReflection.js
  packages/react-reconciler/src/ReactFiberUnwindWork.new.js
  packages/react-reconciler/src/ReactFiberUnwindWork.old.js
  packages/react-reconciler/src/ReactTestSelectors.js
  packages/react-reconciler/src/ReactWorkTags.js
  packages/react-reconciler/src/forks/ReactFiberHostConfig.custom.js
  packages/react-reconciler/src/getComponentNameFromFiber.js
  packages/react-test-renderer/src/ReactTestHostConfig.js
  packages/react-test-renderer/src/ReactTestRenderer.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www-dynamic.js
  packages/shared/forks/ReactFeatureFlags.www.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#25474 Split Cache into its own Dispatcher
  packages/react-debug-tools/src/ReactDebugHooks.js
  packages/react-reconciler/src/ReactFiberCache.new.js
  packages/react-reconciler/src/ReactFiberCache.old.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/ReactInternalTypes.js
  packages/react-server/src/ReactFizzCache.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFizzServer.js
  packages/react-server/src/ReactFlightCache.js
  packages/react-server/src/ReactFlightHooks.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-suspense-test-utils/src/ReactSuspenseTestUtils.js
  packages/react/src/ReactCurrentCache.js
  packages/react/src/ReactCurrentDispatcher.js
  packages/react/src/ReactHooks.js
  packages/react/src/ReactSharedInternals.js
  packages/react/src/forks/ReactCurrentDispatcher.www.js
  packages/react/src/forks/ReactCurrentOwner.www.js
  packages/react/src/forks/ReactSharedInternals.umd.js
  scripts/error-codes/codes.json
  scripts/rollup/forks.js
Labels: CLA Signed

#25475 Remove Shallow Renderer Tests
  packages/react-dom/src/__tests__/ReactTestUtils-test.js
  packages/react-test-renderer/src/__tests__/ReactShallowRenderer-test.js
  packages/react-test-renderer/src/__tests__/ReactShallowRendererHooks-test.js
  packages/react-test-renderer/src/__tests__/ReactShallowRendererMemo-test.js
  scripts/rollup/forks.js
Labels: CLA Signed

#25448 [DevTools][standalone] Stop sending highlight events when a component is selected
  packages/react-devtools-core/src/backend.js
Labels: CLA Signed, React Core Team

#25471 [React Native Meta] dynamic feature flag for ref access warning
  packages/shared/forks/ReactFeatureFlags.native-fb-dynamic.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  scripts/flow/xplat.js
Labels: CLA Signed, React Core Team

#25457 Extract Fizz instruction set to build macro
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/clientRenderFunctionString.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/completeBoundaryFunctionString.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/completeSegmentFunctionString.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/styleInsertionFunctionString.js
Labels: CLA Signed, React Core Team

#25478 React DevTools 4.26.0 -> 4.26.1
  packages/react-devtools-core/package.json
  packages/react-devtools-extensions/chrome/manifest.json
  packages/react-devtools-extensions/edge/manifest.json
  packages/react-devtools-extensions/firefox/manifest.json
  packages/react-devtools-inline/package.json
  packages/react-devtools-timeline/package.json
  packages/react-devtools/CHANGELOG.md
  packages/react-devtools/package.json
Labels: CLA Signed, React Core Team

#25479 Allow Async Functions to be used in Server Components
  packages/react-server-dom-webpack/src/__tests__/ReactFlightDOM-test.js
  packages/react-server/src/ReactFlightServer.js
Labels: CLA Signed

#25465 Initialize useMemoCache with sentinel values
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/__tests__/useMemoCache-test.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFlightHooks.js
  packages/shared/ReactSymbols.js
Labels: CLA Signed, React Core Team

#25481 Add script to generate inline Fizz runtime
  .circleci/config.yml
  package.json
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInlineClientRenderBoundary.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInlineCompleteBoundary.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInlineCompleteBoundaryWithStyles.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInlineCompleteSegment.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInstructionSet.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInstructionSetInlineCodeStrings.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/clientRenderFunctionString.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/completeBoundaryFunctionString.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/completeSegmentFunctionString.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/styleInsertionFunctionString.js
  scripts/rollup/generate-inline-fizz-runtime.js
Labels: CLA Signed, React Core Team

#25482 Scaffolding for react-dom/unstable_external-server-runtime
  packages/react-dom/package.json
  packages/react-dom/src/server/ReactDOMServerExternalRuntime.js
  scripts/rollup/build.js
  scripts/rollup/bundles.js
  scripts/rollup/packaging.js
  scripts/rollup/wrappers.js
  scripts/shared/inlinedHostConfigs.js
Labels: CLA Signed, React Core Team

#25484 Add Jest entry file for external-server-runtime
  packages/react-dom/unstable_server-external-runtime.js
Labels: CLA Signed, React Core Team

#25483 Flow upgrade to 0.190
  package.json
  packages/react-dom-bindings/src/client/ReactDOMComponent.js
  scripts/flow/config/flowconfig
  yarn.lock
Labels: CLA Signed, React Core Team

#25493 Fix download-build script
  scripts/release/shared-commands/get-build-id-for-commit.js
Labels: CLA Signed, React Core Team

#25492 [Flight] Improve Error Messages when Invalid Object is Passed to Client/Host Components
  packages/react-client/src/__tests__/ReactFlight-test.js
  packages/react-server-dom-relay/src/__tests__/ReactFlightDOMRelay-test.internal.js
  packages/react-server-native-relay/src/__tests__/ReactFlightNativeRelay-test.internal.js
  packages/react-server-native-relay/src/__tests__/__snapshots__/ReactFlightNativeRelay-test.internal.js.snap
  packages/react-server/src/ReactFlightServer.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#25498 Enable useMemoCacheHook for ReactNative-fb build
  packages/shared/forks/ReactFeatureFlags.native-fb.js
Labels: CLA Signed, React Core Team

#25495 Bugfix: Suspending in shell during discrete update
  packages/react-dom/src/__tests__/ReactDOMServerSelectiveHydration-test.internal.js
  packages/react-reconciler/src/ReactFiberThrow.new.js
  packages/react-reconciler/src/ReactFiberThrow.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.js
Labels: CLA Signed, React Core Team

#25480 [Float] add support for scripts and other enhancements
  packages/react-dom-bindings/src/client/ReactDOMComponentTree.js
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/client/ReactDOMHostConfig.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInstructionSet.js
  packages/react-dom-bindings/src/server/fizz-instruction-set/ReactDOMFizzInstructionSetInlineCodeStrings.js
  packages/react-dom-bindings/src/shared/ReactDOMResourceValidation.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
  packages/react-dom/src/__tests__/react-dom-server-rendering-stub-test.js
  packages/react-reconciler/src/ReactFiberHostConfigWithNoHydration.js
  packages/react-reconciler/src/ReactFiberHydrationContext.new.js
  packages/react-reconciler/src/ReactFiberHydrationContext.old.js
  packages/react-reconciler/src/forks/ReactFiberHostConfig.custom.js
  scripts/rollup/generate-inline-fizz-runtime.js
Labels: CLA Signed

#25499 Add option to load Fizz runtime from external file
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/server/ReactDOMFizzServerBrowser.js
  packages/react-dom/src/server/ReactDOMFizzServerNode.js
  packages/react-dom/src/server/ReactDOMFizzStaticBrowser.js
  packages/react-dom/src/server/ReactDOMFizzStaticNode.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#25500 move resource acquisition to mutation phase
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
Labels: CLA Signed

#25265 Add detach to Offscreen component
  packages/react-reconciler/src/ReactFiber.new.js
  packages/react-reconciler/src/ReactFiber.old.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberCompleteWork.new.js
  packages/react-reconciler/src/ReactFiberCompleteWork.old.js
  packages/react-reconciler/src/ReactFiberOffscreenComponent.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/__tests__/ReactOffscreen-test.js
  scripts/error-codes/codes.json
Labels: CLA Signed, React Core Team

#25485 refactor: Flow: typing of Scheduler
  packages/scheduler/src/forks/Scheduler.js
Labels: CLA Signed

#25506 Add cache() API
  packages/react-reconciler/src/__tests__/ReactCache-test.js
  packages/react/index.classic.fb.js
  packages/react/index.experimental.js
  packages/react/index.js
  packages/react/index.modern.fb.js
  packages/react/src/React.js
  packages/react/src/ReactCache.js
  packages/react/src/ReactSharedSubset.experimental.js
Labels: CLA Signed

#25387 Remove feature flag enableStrictEffects
  packages/react-reconciler/src/ReactFiber.new.js
  packages/react-reconciler/src/ReactFiber.old.js
  packages/react-reconciler/src/ReactFiberClassComponent.new.js
  packages/react-reconciler/src/ReactFiberClassComponent.old.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/__tests__/ReactOffscreenStrictMode-test.js
  packages/react-reconciler/src/__tests__/StrictEffectsMode-test.js
  packages/react-reconciler/src/__tests__/StrictEffectsModeDefaults-test.internal.js
  packages/react/src/__tests__/ReactStrictMode-test.internal.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www-dynamic.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed, React Core Team

#25473 [useEvent] Non-stable function identity
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactInternalTypes.js
  packages/react-reconciler/src/__tests__/useEvent-test.js
  packages/react-server/src/ReactFizzHooks.js
Labels: CLA Signed, React Core Team

#25512 [useEvent] Lint for presence of useEvent functions in dependency lists
  packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js
  packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js
Labels: CLA Signed, React Core Team

#25516 Add fetch Instrumentation to Dedupe Fetches
  package.json
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFlightCache.js
  packages/react-server/src/ReactFlightHooks.js
  packages/react/src/React.js
  packages/react/src/ReactFetch.js
  packages/react/src/__tests__/ReactFetch-test.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
  yarn.lock
Labels: CLA Signed

#25523 Support `use` in `act` testing API
  packages/react-reconciler/src/ReactFiberWakeable.new.js
  packages/react-reconciler/src/ReactFiberWakeable.old.js
  packages/react-reconciler/src/__tests__/ReactIsomorphicAct-test.js
  packages/react/src/ReactAct.js
  packages/react/src/ReactCurrentActQueue.js
Labels: CLA Signed, React Core Team

#25508 [Float] support title tags as Resources
  packages/react-dom-bindings/src/client/ReactDOMComponentTree.js
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/client/ReactDOMHostConfig.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/shared/HTMLNodeType.js
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
  packages/react-dom/src/__tests__/ReactDOMSingletonComponents-test.js
  packages/react-dom/src/__tests__/ReactRenderDocument-test.js
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
Labels: CLA Signed

#25503 Let ReactDOM initialize in RSC
  packages/react-dom/src/__tests__/ReactDOMInReactServer-test.js
  packages/react-reconciler/src/ReactFiberClassComponent.new.js
  packages/react-reconciler/src/ReactFiberClassComponent.old.js
  packages/react/react.shared-subset.js
  scripts/jest/setupHostConfigs.js
Labels: CLA Signed

#25514 [Float] support meta tags as Resources
  packages/react-dom-bindings/src/client/ReactDOMComponentTree.js
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/client/ReactDOMHostConfig.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
  packages/react-dom/src/__tests__/ReactDOMServerIntegrationAttributes-test.js
  packages/react-dom/src/__tests__/ReactDOMSingletonComponents-test.js
  packages/react-reconciler/src/ReactFiberCommitWork.new.js
  packages/react-reconciler/src/ReactFiberCommitWork.old.js
  scripts/error-codes/codes.json
Labels: CLA Signed

#25145 [DevTools] upgrade to Manifest V3
  packages/react-devtools-extensions/chrome/manifest.json
  packages/react-devtools-extensions/edge/manifest.json
  packages/react-devtools-extensions/firefox/manifest.json
  packages/react-devtools-extensions/src/background.js
  packages/react-devtools-extensions/src/contentScripts/installHook.js
  packages/react-devtools-extensions/src/contentScripts/prepareInjection.js
  packages/react-devtools-extensions/src/contentScripts/proxy.js
  packages/react-devtools-extensions/src/contentScripts/renderer.js
  packages/react-devtools-extensions/src/renderer.js
  packages/react-devtools-extensions/src/utils.js
  packages/react-devtools-extensions/webpack.config.js
  packages/react-devtools-shared/src/devtools/views/Components/Tree.css
  packages/react-devtools-shared/src/devtools/views/Components/Tree.js
  packages/react-devtools/README.md
Labels: CLA Signed, Component: Developer Tools

#25515 [Float] support all links as Resources
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/shared/ReactDOMResourceValidation.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
Labels: CLA Signed

#25534 fix transposed escape functions
  packages/react-dom-bindings/src/server/ReactDOMLegacyServerStreamConfig.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/server/escapeTextForBrowser.js
  packages/react-dom/src/__tests__/ReactDOMFizzServerBrowser-test.js
  packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
  packages/react-server/src/ReactServerStreamConfigBrowser.js
  packages/react-server/src/ReactServerStreamConfigNode.js
Labels: CLA Signed

#25537 Revert yieldy behavior for non-use Suspense
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberThenable.new.js
  packages/react-reconciler/src/ReactFiberThenable.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/__tests__/ReactOffscreenSuspense-test.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.js
  packages/react-reconciler/src/__tests__/ReactThenable-test.js
  packages/react-server/src/ReactFizzHooks.js
  packages/react-server/src/ReactFizzServer.js
  packages/react-server/src/ReactFizzThenable.js
  packages/react-server/src/ReactFlightHooks.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-server/src/ReactFlightThenable.js
  scripts/jest/TestFlags.js
Labels: CLA Signed, React Core Team

#25536 when float is enabled only push title and script as a single unit
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMFizzServerBrowser-test.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
Labels: CLA Signed

#25532 add warnings for non-resources rendered outside body or head
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/client/validateDOMNesting.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
  packages/react-reconciler/src/ReactFiberHostContext.js
  packages/react-reconciler/src/ReactFiberHostContext.new.js
  packages/react-reconciler/src/ReactFiberHostContext.old.js
Labels: CLA Signed

#25540 Revert fetch instrumentation to only RSC
  packages/react/src/React.js
  packages/react/src/ReactSharedSubset.experimental.js
  packages/react/src/__tests__/ReactFetch-test.js
Labels: CLA Signed

#25542 [Flight] Use AsyncLocalStorage to extend the scope of the cache to micro tasks
  .eslintrc.js
  packages/react-dom-bindings/src/server/ReactDOMLegacyServerStreamConfig.js
  packages/react-server-dom-relay/src/ReactFlightDOMRelayServerHostConfig.js
  packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
  packages/react-server-native-relay/src/ReactFlightNativeRelayServerHostConfig.js
  packages/react-server/src/ReactFlightCache.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-server/src/ReactFlightServerConfigStream.js
  packages/react-server/src/ReactServerStreamConfigBrowser.js
  packages/react-server/src/ReactServerStreamConfigNode.js
  packages/react-server/src/forks/ReactServerStreamConfig.custom.js
  packages/react/src/__tests__/ReactFetch-test.js
  scripts/error-codes/codes.json
  scripts/flow/environment.js
  scripts/rollup/bundles.js
  scripts/rollup/validate/eslintrc.cjs.js
  scripts/rollup/validate/eslintrc.cjs2015.js
  scripts/rollup/validate/eslintrc.esm.js
  scripts/rollup/validate/eslintrc.fb.js
  scripts/rollup/validate/eslintrc.rn.js
  scripts/rollup/validate/eslintrc.umd.js
Labels: CLA Signed

#25545 Bug fix when resolving cache
  packages/react-server/src/ReactFlightCache.js
  packages/react/src/__tests__/ReactFetch-test.js
Labels: CLA Signed

#25546 [Float] support <base> as Resource
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
Labels: CLA Signed

#25502 Update cache() and use() to the canary aka next channel
  ReactVersions.js
  fixtures/fizz-ssr-browser/index.html
  fixtures/flight-browser/index.html
  fixtures/flight/src/index.js
  packages/react-client/src/__tests__/ReactFlight-test.js
  packages/react-dom/index.classic.fb.js
  packages/react-dom/index.experimental.js
  packages/react-dom/index.js
  packages/react-dom/index.modern.fb.js
  packages/react-dom/index.stable.js
  packages/react-dom/server-rendering-stub.experimental.js
  packages/react-dom/server-rendering-stub.js
  packages/react-dom/src/__tests__/ReactDOMFizzServer-test.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
  packages/react-dom/src/__tests__/ReactDOMInReactServer-test.js
  packages/react-dom/src/__tests__/ReactWrongReturnPointer-test.js
  packages/react-dom/src/client/ReactDOM.js
  packages/react-dom/src/server/ReactDOMServerRenderingStub.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/__tests__/ReactActWarnings-test.js
  packages/react-reconciler/src/__tests__/ReactCache-test.js
  packages/react-reconciler/src/__tests__/ReactConcurrentErrorRecovery-test.js
  packages/react-reconciler/src/__tests__/ReactContextPropagation-test.js
  packages/react-reconciler/src/__tests__/ReactIsomorphicAct-test.js
  packages/react-reconciler/src/__tests__/ReactSuspenseEffectsSemantics-test.js
  packages/react-reconciler/src/__tests__/ReactSuspenseFallback-test.js
  packages/react-reconciler/src/__tests__/ReactSuspenseWithNoopRenderer-test.js
  packages/react-reconciler/src/__tests__/ReactThenable-test.js
  packages/react-reconciler/src/__tests__/ReactTransition-test.js
  packages/react-server-dom-webpack/package.json
  packages/react-server-dom-webpack/src/__tests__/ReactFlightDOM-test.js
  packages/react-server-dom-webpack/src/__tests__/ReactFlightDOMBrowser-test.js
  packages/react/index.classic.fb.js
  packages/react/index.experimental.js
  packages/react/index.js
  packages/react/index.modern.fb.js
  packages/react/index.stable.js
  packages/react/src/React.js
  packages/react/src/ReactSharedSubset.experimental.js
  packages/react/src/ReactSharedSubset.js
  packages/react/src/__tests__/ReactFetch-test.js
  packages/shared/ReactFeatureFlags.js
  packages/shared/forks/ReactFeatureFlags.native-fb.js
  packages/shared/forks/ReactFeatureFlags.native-oss.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.native.js
  packages/shared/forks/ReactFeatureFlags.test-renderer.www.js
  packages/shared/forks/ReactFeatureFlags.testing.js
  packages/shared/forks/ReactFeatureFlags.testing.www.js
  packages/shared/forks/ReactFeatureFlags.www.js
Labels: CLA Signed

#25554 [Tiny] Fixed incorrect import in `react-server-dom-webpack`
  packages/react-server-dom-webpack/src/ReactFlightWebpackPlugin.js
Labels: CLA Signed

#25560 Flight client error stack
  packages/react-client/src/ReactFlightClient.js
  packages/react-client/src/__tests__/ReactFlight-test.js
Labels: CLA Signed

#25452 [react devtools] Device storage support
  packages/react-devtools-core/src/backend.js
  packages/react-devtools-core/src/cachedSettings.js
  packages/react-devtools-shared/src/backend/agent.js
  packages/react-devtools-shared/src/backend/console.js
  packages/react-devtools-shared/src/bridge.js
  packages/react-devtools-shared/src/utils.js
Labels: CLA Signed

#25569 [Float] fix coordination of resource identity and hydration
  packages/react-dom-bindings/src/client/ReactDOMFloatClient.js
  packages/react-dom-bindings/src/client/ReactDOMHostConfig.js
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
Labels: CLA Signed

#25559 [Float] handle noscript context for Resources
  packages/react-dom-bindings/src/server/ReactDOMFloatServer.js
  packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js
  packages/react-dom-bindings/src/server/ReactDOMServerLegacyFormatConfig.js
  packages/react-dom/src/__tests__/ReactDOMFloat-test.js
Labels: CLA Signed

#25571 Try assigning fetch to globalThis if global assignment fails
  .eslintrc.js
  packages/react/src/ReactFetch.js
  scripts/flow/environment.js
  scripts/rollup/validate/eslintrc.cjs2015.js
  scripts/rollup/validate/eslintrc.esm.js
  scripts/rollup/validate/eslintrc.fb.js
  scripts/rollup/validate/eslintrc.rn.js
  scripts/rollup/validate/eslintrc.umd.js
Labels: CLA Signed

#25577 Remove old react-fetch, react-fs and react-pg libraries
  .eslintrc.js
  ReactVersions.js
  packages/react-fetch/README.md
  packages/react-fetch/index.browser.js
  packages/react-fetch/index.js
  packages/react-fetch/index.node.js
  packages/react-fetch/npm/index.browser.js
  packages/react-fetch/npm/index.js
  packages/react-fetch/npm/index.node.js
  packages/react-fetch/package.json
  packages/react-fetch/src/ReactFetchBrowser.js
  packages/react-fetch/src/ReactFetchNode.js
  packages/react-fetch/src/__tests__/ReactFetchBrowser-test.js
  packages/react-fetch/src/__tests__/ReactFetchNode-test.js
  packages/react-fs/README.md
  packages/react-fs/index.browser.server.js
  packages/react-fs/index.js
  packages/react-fs/index.node.server.js
  packages/react-fs/npm/index.browser.server.js
  packages/react-fs/npm/index.js
  packages/react-fs/npm/index.node.server.js
  packages/react-fs/package.json
  packages/react-fs/src/ReactFilesystem.js
  packages/react-pg/README.md
  packages/react-pg/index.browser.server.js
  packages/react-pg/index.js
  packages/react-pg/index.node.server.js
  packages/react-pg/npm/index.browser.server.js
  packages/react-pg/npm/index.js
  packages/react-pg/npm/index.node.server.js
  packages/react-pg/package.json
  packages/react-pg/src/ReactPostgres.js
  scripts/rollup/bundles.js
  scripts/rollup/modules.js
Labels: CLA Signed

#25543 Detect and warn if use(promise) is wrapped with try/catch block
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberThenable.new.js
  packages/react-reconciler/src/ReactFiberThenable.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
  packages/react-reconciler/src/__tests__/ReactThenable-test.js
  packages/react-server/src/ReactFizzServer.js
  packages/react-server/src/ReactFizzThenable.js
  packages/react-server/src/ReactFlightServer.js
  packages/react-server/src/ReactFlightThenable.js
  scripts/error-codes/codes.json
Labels: CLA Signed, React Core Team

#25583 Strict Mode: Reuse memoized result from first pass
  packages/react-reconciler/src/ReactFiberBeginWork.new.js
  packages/react-reconciler/src/ReactFiberBeginWork.old.js
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react/src/__tests__/ReactStrictMode-test.js
Labels: CLA Signed, React Core Team

#25587 Clean up vestige of useOpaqueIdentifier
  packages/react-reconciler/src/ReactFiberHooks.new.js
  packages/react-reconciler/src/ReactFiberHooks.old.js
  packages/react-reconciler/src/ReactFiberWorkLoop.new.js
  packages/react-reconciler/src/ReactFiberWorkLoop.old.js
Labels: CLA Signed, React Core Team

#25595 Fix type check for null
  packages/react-server/src/ReactFlightServer.js
Labels: CLA Signed
